### ISSUE TITLE
(libretro) Crashes on startup with asan

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#10410]
## Description

When testing the libretro core with RetroArch built with asan support it will crash when booting content. I have not tried this with the SDL2 or Qt5 frontends as I am not sure how to build them with asan? Although this occurs with RetroArch I am reporting this here under the suggestion of @hrydgard. See the original issue here. https://github.com/libretro/ppsspp/issues/12

### Expected behavior

It should not crash.

### Actual behavior

It crashes when booting content.

gcc-7.2.0
```
53:19:048 Core/System.cpp:397 I[BOOT]: PPSSPP v1.4.2-git
53:19:050 Core/MemMap.cpp:291 I[MEMMAP]: Memory system initialized. Base at 0x2300000000 (RAM at @ 0x2308000000, uncached @ 0x2348000000)
53:19:052 Core/PSPLoaders.cpp:193 I[LOADER]: ULES00176 : Tales of Eternia
53:19:053 Core/Config.cpp:1378 I[LOADER]: Failed to read ULES00176_ppsspp.ini. No game-specific settings found, using global defaults.
53:19:053 Core/PSPLoaders.cpp:252 I[LOADER]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
53:19:053 HLE/sceKernelMemory.cpp:434 I[SCEKERNEL]: Kernel and user memory pools initialized
ASAN:DEADLYSIGNAL
=================================================================
==11020==ERROR: AddressSanitizer: SEGV on unknown address 0x0004e0ff8000 (pc 0x7f367ecf6374 bp 0x7ffc0a9fe740 sp 0x7ffc0a9fdec0 T0)
==11020==The signal is caused by a READ memory access.
    #0 0x7f367ecf6373  (/usr/lib64/libasan.so.4+0x76373)
    #1 0x7f366c178daf in Memory::Memcpy(unsigned int, void const*, unsigned int) ../Core/MemMapHelpers.h:35
    #2 0x7f366c266230 in __KernelThreadingInit() ../Core/HLE/sceKernelThread.cpp:928
    #3 0x7f366c212ac0 in __KernelInit() ../Core/HLE/sceKernel.cpp:110
    #4 0x7f366c24562b in __KernelLoadReset() ../Core/HLE/sceKernelModule.cpp:1552
    #5 0x7f366c245730 in __KernelLoadExec(char const*, unsigned int, std::string*) ../Core/HLE/sceKernelModule.cpp:1577
    #6 0x7f366c333e95 in Load_PSP_ISO(FileLoader*, std::string*) ../Core/PSPLoaders.cpp:253
    #7 0x7f366c2dde69 in LoadFile(FileLoader**, std::string*) ../Core/Loaders.cpp:287
    #8 0x7f366c34418e in CPU_Init() ../Core/System.cpp:265
    #9 0x7f366c3446f7 in PSP_InitStart(CoreParameter const&, std::string*) ../Core/System.cpp:417
    #10 0x7f366c344889 in PSP_Init(CoreParameter const&, std::string*) ../Core/System.cpp:452
    #11 0x7f366c355ee7 in retro_run ../libretro/libretro.cpp:1187
    #12 0x41eced in core_run /tmp/SBo/RetroArch-1.6.9/core_impl.c:415
    #13 0x427672 in runloop_iterate /tmp/SBo/RetroArch-1.6.9/retroarch.c:3120
    #14 0x41bf88 in rarch_main frontend/frontend.c:131
    #15 0x41c0be in main frontend/frontend.c:151
    #16 0x7f3677429029 in __libc_start_main (/lib64/libc.so.6+0x21029)
    #17 0x412d19 in _start (/usr/games/retroarch+0x412d19)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib64/libasan.so.4+0x76373) 
==11020==ABORTING
```
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007ffff6e9a374 in ?? () from /usr/lib64/libasan.so.4
(gdb) bt
#0  0x00007ffff6e9a374 in ?? () from /usr/lib64/libasan.so.4
#1  0x00007fffe437edb0 in Memory::Memcpy (to_address=134217728,
    from_data=0x7fffe4eb5d70 <__KernelThreadingInit()::idleThreadCode>, len=16)
    at ../Core/MemMapHelpers.h:35
#2  0x00007fffe446c231 in __KernelThreadingInit ()
    at ../Core/HLE/sceKernelThread.cpp:928
#3  0x00007fffe4418ac1 in __KernelInit () at ../Core/HLE/sceKernel.cpp:110
#4  0x00007fffe444b62c in __KernelLoadReset ()
    at ../Core/HLE/sceKernelModule.cpp:1552
#5  0x00007fffe444b731 in __KernelLoadExec (
    filename=0x6060002a9ab8 "disc0:/PSP_GAME/SYSDIR/EBOOT.BIN", paramPtr=0,
    error_string=0x7fffe4f03518 <coreParameter+56>)
    at ../Core/HLE/sceKernelModule.cpp:1577
#6  0x00007fffe4539e96 in Load_PSP_ISO (fileLoader=0x603000494650,
    error_string=0x7fffe4f03518 <coreParameter+56>) at ../Core/PSPLoaders.cpp:253
#7  0x00007fffe44e3e6a in LoadFile (fileLoaderPtr=0x7fffe4f03568 <loadedFile>,
    error_string=0x7fffe4f03518 <coreParameter+56>) at ../Core/Loaders.cpp:287
#8  0x00007fffe454a18f in CPU_Init () at ../Core/System.cpp:265
#9  0x00007fffe454a6f8 in PSP_InitStart (coreParam=...,
    error_string=0x7fffffffde98) at ../Core/System.cpp:417
#10 0x00007fffe454a88a in PSP_Init (coreParam=..., error_string=0x7fffffffde98)
    at ../Core/System.cpp:452
#11 0x00007fffe455bee8 in retro_run () at ../libretro/libretro.cpp:1187
#12 0x000000000041ecee in core_run () at core_impl.c:415
#13 0x0000000000427673 in runloop_iterate (sleep_ms=0x7fffffffdff0)
    at retroarch.c:3120
#14 0x000000000041bf89 in rarch_main (argc=4, argv=0x7fffffffe1a8, data=0x0)
    at frontend/frontend.c:131
#15 0x000000000041c0bf in main (argc=4, argv=0x7fffffffe1a8)
    at frontend/frontend.c:151
```
Full GDB log - https://pastebin.com/Q0QHxfJ1

clang-5.0.0
```
07:54:078 Core/System.cpp:397 I[BOOT]: PPSSPP v1.4.2-git
07:54:080 Core/MemMap.cpp:291 I[MEMMAP]: Memory system initialized. Base at 0x2300000000 (RAM at @ 0x2308000000, uncached @ 0x2348000000)
07:54:082 Core/PSPLoaders.cpp:193 I[LOADER]: ULES00176 : Tales of Eternia
07:54:082 Core/Config.cpp:1378 I[LOADER]: Failed to read ULES00176_ppsspp.ini. No game-specific settings found, using global defaults.
07:54:082 Core/PSPLoaders.cpp:252 I[LOADER]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
07:54:082 HLE/sceKernelMemory.cpp:434 I[SCEKERNEL]: Kernel and user memory pools initialized
ASAN:DEADLYSIGNAL
=================================================================
==19191==ERROR: AddressSanitizer: SEGV on unknown address 0x0004e0ff8000 (pc 0x000000440008 bp 0x7ffe8ee991a0 sp 0x7ffe8ee98928 T0)
==19191==The signal is caused by a READ memory access.
    #0 0x440007 in AddressIsPoisoned /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/asan_mapping.h:321:29
    #1 0x440007 in __asan::QuickCheckForUnpoisonedRegion(unsigned long, unsigned long) /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:44
    #2 0x447229 in memcpy /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:738:5
    #3 0x7f3df6878daf in Memory::Memcpy(unsigned int, void const*, unsigned int) /media/gittings/forks/libretro/ppsspp/libretro/../Core/MemMapHelpers.h:35
    #4 0x7f3df6966230 in __KernelThreadingInit() /media/gittings/forks/libretro/ppsspp/libretro/../Core/HLE/sceKernelThread.cpp:928
    #5 0x7f3df6912ac0 in __KernelInit() /media/gittings/forks/libretro/ppsspp/libretro/../Core/HLE/sceKernel.cpp:110
    #6 0x7f3df694562b in __KernelLoadReset() /media/gittings/forks/libretro/ppsspp/libretro/../Core/HLE/sceKernelModule.cpp:1552
    #7 0x7f3df6945730 in __KernelLoadExec(char const*, unsigned int, std::string*) /media/gittings/forks/libretro/ppsspp/libretro/../Core/HLE/sceKernelModule.cpp:1577
    #8 0x7f3df6a33e95 in Load_PSP_ISO(FileLoader*, std::string*) /media/gittings/forks/libretro/ppsspp/libretro/../Core/PSPLoaders.cpp:253
    #9 0x7f3df69dde69 in LoadFile(FileLoader**, std::string*) /media/gittings/forks/libretro/ppsspp/libretro/../Core/Loaders.cpp:287
    #10 0x7f3df6a4418e in CPU_Init() /media/gittings/forks/libretro/ppsspp/libretro/../Core/System.cpp:265
    #11 0x7f3df6a446f7 in PSP_InitStart(CoreParameter const&, std::string*) /media/gittings/forks/libretro/ppsspp/libretro/../Core/System.cpp:417
    #12 0x7f3df6a44889 in PSP_Init(CoreParameter const&, std::string*) /media/gittings/forks/libretro/ppsspp/libretro/../Core/System.cpp:452
    #13 0x7f3df6a55ee7 in retro_run /media/gittings/forks/libretro/ppsspp/libretro/../libretro/libretro.cpp:1187
    #14 0x50beaf in core_run /tmp/SBo/RetroArch-1.6.9/core_impl.c:415:4
    #15 0x5133db in runloop_iterate /tmp/SBo/RetroArch-1.6.9/retroarch.c:3120:4
    #16 0x5072ba in rarch_main /tmp/SBo/RetroArch-1.6.9/frontend/frontend.c:131:27
    #17 0x507695 in main /tmp/SBo/RetroArch-1.6.9/frontend/frontend.c:151:11
    #18 0x7f3e01bb1029 in __libc_start_main (/lib64/libc.so.6+0x21029)
    #19 0x42d889 in _start /root/glibc-tmp-c9e38902b3017cc77fdedd43425fb917/glibc-2.26/csu/../sysdeps/x86_64/start.S:120

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/asan_mapping.h:321:29 in AddressIsPoisoned
==19191==ABORTING
```
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
AddressIsPoisoned ()
    at /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/asan_mapping.h:322
322 /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/asan_mapping.h: No such file or directory.
(gdb) bt
#0  AddressIsPoisoned ()
    at /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/asan_mapping.h:322
#1  QuickCheckForUnpoisonedRegion ()
    at /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:44
#2  0x000000000044722a in __interceptor_memcpy ()
    at /tmp/llvm-5.0.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:738
#3  0x00007fffe537edb0 in Memory::Memcpy (to_address=134217728,
    from_data=0x7fffe5eb5d70 <__KernelThreadingInit()::idleThreadCode>, len=16)
    at ../Core/MemMapHelpers.h:35
#4  0x00007fffe546c231 in __KernelThreadingInit ()
    at ../Core/HLE/sceKernelThread.cpp:928
#5  0x00007fffe5418ac1 in __KernelInit () at ../Core/HLE/sceKernel.cpp:110
#6  0x00007fffe544b62c in __KernelLoadReset ()
    at ../Core/HLE/sceKernelModule.cpp:1552
#7  0x00007fffe544b731 in __KernelLoadExec (
    filename=0x6060002a9ab8 "disc0:/PSP_GAME/SYSDIR/EBOOT.BIN", paramPtr=0,
    error_string=0x7fffe5f03518 <coreParameter+56>)
    at ../Core/HLE/sceKernelModule.cpp:1577
#8  0x00007fffe5539e96 in Load_PSP_ISO (fileLoader=0x603000494650,
    error_string=0x7fffe5f03518 <coreParameter+56>) at ../Core/PSPLoaders.cpp:253
#9  0x00007fffe54e3e6a in LoadFile (fileLoaderPtr=0x7fffe5f03568 <loadedFile>,
    error_string=0x7fffe5f03518 <coreParameter+56>) at ../Core/Loaders.cpp:287
#10 0x00007fffe554a18f in CPU_Init () at ../Core/System.cpp:265
#11 0x00007fffe554a6f8 in PSP_InitStart (coreParam=...,
    error_string=0x7fffffffdbb8) at ../Core/System.cpp:417
#12 0x00007fffe554a88a in PSP_Init (coreParam=..., error_string=0x7fffffffdbb8)
    at ../Core/System.cpp:452
#13 0x00007fffe555bee8 in retro_run () at ../libretro/libretro.cpp:1187
#14 0x000000000050beb0 in core_run () at core_impl.c:415
#15 0x00000000005133dc in runloop_iterate (sleep_ms=0x7fffffffdf60)
    at retroarch.c:3120
#16 0x00000000005072bb in rarch_main (argc=4, argv=0x7fffffffe1a8, data=0x0)
    at frontend/frontend.c:131
#17 0x0000000000507696 in main (argc=4, argv=0x7fffffffe1a8)
    at frontend/frontend.c:151
```
Full GDB log - https://pastebin.com/dh7yuuke

### Steps to reproduce the bug

1. Build RetroArch with `SANITIZER=address`
2. Start content with the ppsspp core.
3. It crashes.

### Bisect Results

This also occurred with the old and out of date libretro core so I don't think its worth going back further than that.

### Version/Commit

- RetroArch: `1.6.9`
- ppsspp: https://github.com/hrydgard/ppsspp/pull/10407

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-7.2.0`, `clang-5.0.0`

@bparker06 Bringing your attention to this issue since you originally reported it.

**Comment by hrydgard** [comment]
I believe this is ASAN misunderstanding our memory map tricks. We map the PSP RAM into multiple places to simulate the memory map of the real PSP (RAM is visible at both 0x08000000 and 0x48000000 (uncached), and additionally at 0x88000000 if you're the kernel). Not sure what we can do about it.

**Comment by orbea** [comment]
That is understandable if its difficult to fix. As this feature is mostly used for debugging most users will probably not notice, but it would be nice to fix when possible as it could help expose obscured issues in the future.

I tried inviting @bparker06 to this issue as he knows a lot more about asan than I do, but I suspect he's currently busy with other priorities.

**Comment by hrydgard** [comment]
Yeah, would be great if we could get it working. Is there a way to exclude memory ranges from ASAN tracking?

**Comment by hrydgard** [comment]
Added an option --sanitize to b.sh (CMake option USE_ADDRESS_SANITIZER) which now turns off the things that are problematic with the sanitizer, so it's now usable!

**Comment by orbea** [comment]
Awesome, thanks!

**Comment by orbea** [comment]
That is good to know, but likewise working on Linux is enough for my specific use case.
