### ISSUE TITLE
Dynasty Warrior strikeforce multiplayer issue

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13186]
I have tested that we can enter the city just fine, even can see each other but when send item trade or friend request and also accept request, other player can't accept because there is no windows or notifications so we can't enter the mission only stuck in the city.

**Comment by adenovan** [comment]
log please

**Comment by Lemoncak3** [comment]
How to get a log in PPSSPP? Never get one before..

**Comment by adenovan** [comment]
Settings->Tools->Developer Tools->Debug Logging

**Comment by Saramagrean** [comment]
Try change WLAN channel to 1, It work for WO2 (but gameplay so slow),  think it will work? because it is the Musou series from the same game developer.
![WO2](https://user-images.githubusercontent.com/26355472/89121004-48129c80-d4e5-11ea-8484-3c8d8aeaaa0f.png)

**Comment by Lemoncak3** [comment]
Have tested with all wlan channel with still same issue 
![Screenshot_20200816-042839](https://user-images.githubusercontent.com/67026697/90322086-20f2ab00-df7a-11ea-841a-fbd53f6b8549.png)
My brother can join just fine but when i send item trade request and friend request, he didn't receive anything.
![Screenshot_20200816-042855](https://user-images.githubusercontent.com/67026697/90322092-3b2c8900-df7a-11ea-9c9b-3ec7b1efcbb0.png)

**Comment by Lemoncak3** [comment]
Okay will download the latest build and will inform you the result

**Comment by ANR2ME** [comment]
> 
> 
> Okay will download the latest build and will inform you the result

it's not built yet, you need to wait until that PR appeared on https://buildbot.orphis.net/ppsspp/

**Comment by Lemoncak3** [comment]
Have tested it but from client side it shows this error
![IMG-20200912-WA0000](https://user-images.githubusercontent.com/67026697/92969473-41ddeb80-f4a7-11ea-9957-783d89bb6b5d.jpg)
and from my side as the server tried to accept quest, the client side still haven't receive anything
![Screenshot_20200912-031604](https://user-images.githubusercontent.com/67026697/92969550-5fab5080-f4a7-11ea-9aef-02586c608f84.png)
And when i send item trade or friend request this error shows in my screen 
![Screenshot_20200912-030241](https://user-images.githubusercontent.com/67026697/92969593-76ea3e00-f4a7-11ea-8fa9-8da51cede3bd.png)

**Comment by ANR2ME** [comment]
Have you tried using Port Offset 10000? The game must not shows any red message on screen in order to work properly.

Regarding the crash on exit, i didn't experiencing it when testing PSP2 and VK2, i'll test again using this game later.

**Comment by Lemoncak3** [comment]
![Screenshot_20200912-042226](https://user-images.githubusercontent.com/67026697/92974163-d2202e80-f4af-11ea-87cf-9005c471b033.png)
This is from my side as adhoc server when sending item trade

**Comment by ANR2ME** [comment]
Hmm.. if it keeps appearing regardless the port offset value, high possibility it's Android limitation not allowing to reuse already used ports :(

**Comment by ANR2ME** [comment]
Okay, i've fixed the Port Binding issue, however multiplayer on this games seems to be running like a slideshow on android, while it's smooth on Windows.

The Logcat are filled with
```
2020-09-12 07:00:48.264 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 2 lines
2020-09-12 07:00:48.296 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 2 lines
2020-09-12 07:00:48.329 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 2 lines
2020-09-12 07:00:48.360 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 2 lines
2020-09-12 07:00:48.392 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 2 lines
2020-09-12 07:00:48.421 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 1 line
2020-09-12 07:00:48.456 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 2 lines
2020-09-12 07:00:48.484 5020-5332/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2020-09-12 07:00:48.489 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 1 line
2020-09-12 07:00:48.521 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 2 lines
2020-09-12 07:00:48.552 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack 
```

there are also a very long exception related to Firebase
```
2020-09-12 07:00:47.016 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 1 line
2020-09-12 07:00:47.022 4786-4931/? E/FirebaseCrashlytics: Create report HTTP request failed.
    java.net.ConnectException: Failed to connect to reports.crashlytics.com/::1:443
        at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:14)
        at okhttp3.internal.connection.RealConnection.connect(SourceFile:14)
        at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:37)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:1)
        at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:6)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:5)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
        at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:22)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
        at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:22)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:9)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
        at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:13)
        at okhttp3.RealCall.execute(SourceFile:9)
        at com.google.firebase.crashlytics.c.l.b.b(SourceFile:3)
        at com.google.firebase.crashlytics.c.o.d.c.a(SourceFile:5)
        at com.google.firebase.crashlytics.c.o.d.a.a(SourceFile:3)
        at com.google.firebase.crashlytics.c.o.b.d(SourceFile:9)
        at com.google.firebase.crashlytics.c.o.b$d.b(SourceFile:11)
        at com.google.firebase.crashlytics.c.o.b$d.a(SourceFile:1)
        at com.google.firebase.crashlytics.c.h.d.run(SourceFile:2)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.ConnectException: failed to connect to reports.crashlytics.com/::1 (port 443) from /::1 (port 39752) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:278)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:187)
        at libcore.io.IoBridge.connect(IoBridge.java:129)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(SourceFile:1)
        at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:9)
        at okhttp3.internal.connection.RealConnection.connect(SourceFile:14) 
        at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:37) 
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:1) 
        at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:6) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:5) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:22) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:22) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:9) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:13) 
        at okhttp3.RealCall.execute(SourceFile:9) 
        at com.google.firebase.crashlytics.c.l.b.b(SourceFile:3) 
        at com.google.firebase.crashlytics.c.o.d.c.a(SourceFile:5) 
        at com.google.firebase.crashlytics.c.o.d.a.a(SourceFile:3) 
        at com.google.firebase.crashlytics.c.o.b.d(SourceFile:9) 
        at com.google.firebase.crashlytics.c.o.b$d.b(SourceFile:11) 
        at com.google.firebase.crashlytics.c.o.b$d.a(SourceFile:1) 
        at com.google.firebase.crashlytics.c.h.d.run(SourceFile:2) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
```

And exception related to okhttp/facebook
```
2020-09-12 07:00:51.304 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical 2 lines
2020-09-12 07:00:51.311 13268-13361/? W/System.err: java.net.SocketTimeoutException: failed to connect to web.facebook.com/31.13.77.17 (port 443) from /10.121.122.216 (port 38242) after 30000ms
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:129)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at java.net.Socket.connect(Socket.java:621)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2020-09-12 07:00:51.311 13268-13361/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.facebook.ads.redexgen.X.7h.A01(:16256)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.facebook.ads.redexgen.X.7h.A0I(:16429)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.facebook.ads.redexgen.X.Ez.A00(:24303)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at com.facebook.ads.redexgen.X.Ez.doInBackground(:24323)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-09-12 07:00:51.312 13268-13361/? W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-09-12 07:00:51.313 26318-26318/? A/linker: CANNOT LINK EXECUTABLE "/system/bin/dpmd": "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit
2020-09-12 07:00:51.336 25152-25252/? I/chatty: uid=10387(org.ppsspp.ppsspp) AudioTrack identical
```

**Comment by Saramagrean** [comment]
I have a question :), Port offset it need restart app for apply?

**Comment by ANR2ME** [comment]
> 
> 
> I have a question :), Port offset it need restart app for apply?

Yes, these are precalculated or cached on different variables.
```
	portOffset = g_Config.iPortOffset;
	isOriPort = g_Config.bEnableUPnP && g_Config.bUPnPUseOriginalPort;
	minSocketTimeoutUS = g_Config.iMinTimeout * 1000UL;
```
The reason for portOffset to be cached on a different var is to prevent it from being changed after already used by UPnP/PortManager, so PortManager can keep tracks of opened ports and able to restore them (if they were taken over from different app/service) or close all opened ports properly.

**Comment by Lemoncak3** [comment]
Have tried it, whoever enter the city first will lag after another player enter the multiplayer city. And the latest one will get no lag at all. I don't know about third or fourth player though since i only tried for two player

**Comment by ANR2ME** [comment]
It started lagging as bad as a slideshow if one player initiate a Trade, the one who initiate a Trade won't lag but the other player chosen to trade with will get extremely lag. 
Not really sure what the game is trying to do here during a Trade, but Windows doesn't face this issue (at least on localhost, not sure about PC vs PC since i don't have another PC)

**Comment by Lemoncak3** [comment]
In my case the lag started as soon as other player join the city. The second player can running around freely without lag at all. The one who iniated trade in my case are the second player who has no lag but the first one are so lag maybe the trade initiated but it take a very very long time to open if it's opened.

**Comment by MojoJojoDojo** [comment]
Someone told me that Dissidia Android to PC also got that issue (lags on android).

**Comment by ANR2ME** [comment]
> 
> 
> Someone told me that Dissidia Android to PC also got that issue (lags on android).

I can reproduce this, but only when Android is the Host, once someone joined FPS/VPS dropped from30/30 (99.9%) to 1/30 (3.3%)

**Comment by ANR2ME** [comment]
@Lemoncak3  could you test this game again later after PR https://github.com/hrydgard/ppsspp/pull/13432 gets merged

**Comment by DarkBringgX** [comment]
Hmmm... Already fix the FPS drop??
. 
Someone want to try this with me??

**Comment by ANR2ME** [comment]
> Hmmm... Already fix the FPS drop??
> .
> Someone want to try this update with me??

yes it's fixed, it should runs at full speed now

**Comment by DarkBringgX** [comment]
> ![Screenshot_20200912-042226](https://user-images.githubusercontent.com/67026697/92974163-d2202e80-f4af-11ea-87cf-9005c471b033.png)
> This is from my side as adhoc server when sending item trade
> ![IMG-20200912-WA0001](https://user-images.githubusercontent.com/67026697/92974210-ebc17600-f4af-11ea-8aaa-01df3260c0e2.jpg)
> This is from my brother's handphone. We're using port offset 10000

. 
Which patch do you use for this game??
. Are you download the V3.

**Comment by Lemoncak3** [comment]
I have tried it, it worked wonderfully now both player are moving smoothly now. Item trade and quest board worked too now so can get into the mission.
![Screenshot_20200915-134202](https://user-images.githubusercontent.com/67026697/93175729-4aaa1800-f75a-11ea-82f0-6f50a850c567.png)
![Screenshot_20200915-134230](https://user-images.githubusercontent.com/67026697/93175734-4da50880-f75a-11ea-9e10-a187abb668bc.png)
![Screenshot_20200915-134243](https://user-images.githubusercontent.com/67026697/93175741-50076280-f75a-11ea-8450-0e16cebe07b1.png)
![Screenshot_20200915-134343](https://user-images.githubusercontent.com/67026697/93175747-5269bc80-f75a-11ea-9427-5bbdeb041dea.png)

**Comment by Lemoncak3** [comment]
> > ![Screenshot_20200912-042226](https://user-images.githubusercontent.com/67026697/92974163-d2202e80-f4af-11ea-87cf-9005c471b033.png)
> > This is from my side as adhoc server when sending item trade
> > ![IMG-20200912-WA0001](https://user-images.githubusercontent.com/67026697/92974210-ebc17600-f4af-11ea-8aaa-01df3260c0e2.jpg)
> > This is from my brother's handphone. We're using port offset 10000
> 
> .
> @Lemoncak3 Which patch do you use for this game??
> . Are you download the V3.

I am using the latest build from automated PPSSPP build

**Comment by MojoJojoDojo** [comment]
@ANR2ME Now instead of this game being too slow while in multiplayer , Kingdom Hearts is too slow on android (pc is fine).
@zakilj3 could confirm.
