### ISSUE TITLE
[UBSAN] jpge: left shift of negative value

### ISSUE THREAD

**Issue by glebm** [hrydgard/ppsspp#14012]
This warning is completely benign (two's complement will be required in newer C++ editions) but is trivial to fix by updating jpeg-compressor from upstream https://github.com/richgel999/jpeg-compressor

```
../ext/jpge/jpgd.cpp:167:54: runtime error: left shift of negative value -838
    #0 0x5567eb92971a in jpgd::Col<8>::idct(unsigned char*, int const*) ../ext/jpge/jpgd.cpp:167
    #1 0x5567eb8faba5 in jpgd::idct(short const*, unsigned char*, int) ../ext/jpge/jpgd.cpp:305
    #2 0x5567eb901a3d in jpgd::jpeg_decoder::transform_mcu_expand(int) ../ext/jpge/jpgd.cpp:1525
    #3 0x5567eb906019 in jpgd::jpeg_decoder::decode_next_row() ../ext/jpge/jpgd.cpp:1859
    #4 0x5567eb90a827 in jpgd::jpeg_decoder::decode(void const**, unsigned int*) ../ext/jpge/jpgd.cpp:2140
    #5 0x5567eb916dd8 in jpgd::decompress_jpeg_image_from_stream(jpgd::jpeg_decoder_stream*, int*, int*, int*, int) ../ext/jpge/jpgd.cpp:3093
    #6 0x5567eb917a30 in jpgd::decompress_jpeg_image_from_memory(unsigned char const*, int, int*, int*, int*, int) ../ext/jpge/jpgd.cpp:3161
    #7 0x5567ea858223 in LoadTextureLevels ../UI/TextureUtil.cpp:82
    #8 0x5567ea85850c in ManagedTexture::LoadFromFileData(unsigned char const*, unsigned long, ImageFileType, bool, char const*) ../UI/TextureUtil.cpp:109
    #9 0x5567ea859018 in ManagedTexture::LoadFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ImageFileType, bool) ../UI/TextureUtil.cpp:157
    #10 0x5567ea8592ef in CreateTextureFromFile(Draw::DrawContext*, char const*, ImageFileType, bool) ../UI/TextureUtil.cpp:173
    #11 0x5567ea6f24c1 in AsyncImageFileView::Draw(UIContext&) ../UI/PauseScreen.cpp:126
    #12 0x5567eb8a3eac in UI::ViewGroup::Draw(UIContext&) ../Common/UI/ViewGroup.cpp:149
    #13 0x5567ea6f5656 in SaveSlotView::Draw(UIContext&) ../UI/PauseScreen.cpp:274
    #14 0x5567eb8a3eac in UI::ViewGroup::Draw(UIContext&) ../Common/UI/ViewGroup.cpp:149
    #15 0x5567eb8b04c3 in UI::ScrollView::Draw(UIContext&) ../Common/UI/ViewGroup.cpp:780
    #16 0x5567eb8a3eac in UI::ViewGroup::Draw(UIContext&) ../Common/UI/ViewGroup.cpp:149
    #17 0x5567eb84856d in UIScreen::render() ../Common/UI/UIScreen.cpp:121
    #18 0x5567eb82ef49 in ScreenManager::render() ../Common/UI/Screen.cpp:167
    #19 0x5567ea5c0d24 in NativeRender(GraphicsContext*) ../UI/NativeApp.cpp:1094
    #20 0x5567ea8a784e in UpdateRunLoop() ../Core/Core.cpp:208
    #21 0x5567eb8ebdf5 in main ../SDL/SDLMain.cpp:1084
    #22 0x7f37871e3cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
    #23 0x5567ea5b6bad in _start (/home/gleb/repos/glebm/ppsspp/build/PPSSPPSDL+0x221dbad)
```

**Comment by hrydgard** [comment]
yup, will do after the release.
