### ISSUE TITLE
[UBSAN] ext/snappy/snappy-stubs-internal.h load of misaligned address

### ISSUE THREAD

**Issue by glebm** [hrydgard/ppsspp#14013]
In God of War:

```
../ext/snappy/snappy-stubs-internal.h:357:20: runtime error: load of misaligned address 0x55a1373331e2 for type 'const uint32', which requires 4 byte alignment
0x55a1373331e2: note: pointer points here
 17 05  e0 f0 43 43 00 00 30 fb  19 00 f4 0c 10 da 03 00  00 b3 df 03 50 89 bf 20  fa cf ba ba 05 00
              ^ 
    #0 0x55a1306f0eab in snappy::LittleEndian::Load32(void const*) ../ext/snappy/snappy-stubs-internal.h:357
    #1 0x55a1306f0eab in void snappy::SnappyDecompressor::DecompressAllTags<snappy::SnappyArrayWriter>(snappy::SnappyArrayWriter*) ../ext/snappy/snappy.cpp:867
    #2 0x55a1306f0eab in InternalUncompressAllTags<snappy::SnappyArrayWriter> ../ext/snappy/snappy.cpp:989
    #3 0x55a1306f0eab in InternalUncompress<snappy::SnappyArrayWriter> ../ext/snappy/snappy.cpp:975
    #4 0x55a1306f0eab in snappy::RawUncompress(snappy::Source*, char*) ../ext/snappy/snappy.cpp:1342
    #5 0x55a1306f11bc in snappy::RawUncompress(char const*, unsigned long, char*) ../ext/snappy/snappy.cpp:1337
    #6 0x55a1306e9b9b in snappy_uncompress ../ext/snappy/snappy-c.cpp:58
    #7 0x55a130366618 in CChunkFileReader::LoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned char*&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ../Common/Serialize/Serializer.cpp:274
    #8 0x55a12fc34e5f in CChunkFileReader::Error CChunkFileReader::Load<SaveState::SaveStart>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, SaveState::SaveStart&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ../Common/Serialize/Serializer.h:181
    #9 0x55a12fc2c1eb in SaveState::Process() ../Core/SaveState.cpp:761
    #10 0x55a12fc448b1 in PSP_RunLoopUntil(unsigned long long) ../Core/System.cpp:548
    #11 0x55a12fc44a68 in PSP_RunLoopFor(int) ../Core/System.cpp:561
    #12 0x55a12fc44861 in PSP_RunLoopWhileState() ../Core/System.cpp:539
    #13 0x55a12f3b7eaf in EmuScreen::render() ../UI/EmuScreen.cpp:1520
    #14 0x55a130584fe7 in ScreenManager::render() ../Common/UI/Screen.cpp:167
    #15 0x55a12f316d24 in NativeRender(GraphicsContext*) ../UI/NativeApp.cpp:1094
    #16 0x55a12f5fd858 in UpdateRunLoop() ../Core/Core.cpp:208
    #17 0x55a130641e93 in main ../SDL/SDLMain.cpp:1084
    #18 0x7fb6c8dd1cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
    #19 0x55a12f30cbad in _start (/home/gleb/repos/glebm/ppsspp/build/PPSSPPSDL+0x21d7bad)
```

**Comment by glebm** [comment]
This can be fixed by simply updating snappy

Fixed upstream in https://github.com/google/snappy/commit/041c608086d00ceb8285b91f034cfa8b84c83d7c (great commit message btw)
