### ISSUE TITLE
[UBSAN] GPU/Common/DrawEngineCommon.cpp:614 - load of misaligned address

### ISSUE THREAD

**Issue by glebm** [hrydgard/ppsspp#14025]
```
../GPU/Common/DrawEngineCommon.cpp:614:13: runtime error: load of misaligned address 0x7fde0414e589 for type 'const u32', which requires 4 byte alignment
0x7fde0414e589: note: pointer points here
 05 06 07  08 09 0a 0b 0c 0d 0e 0f  10 11 0b 12 13 14 15 16  17 18 19 13 0b 1a 1b 1c  1d 1e 1f 10 20
              ^ 
    #0 0x563fa63670c9 in ComputeMiniHashRange(void const*, unsigned long) ../GPU/Common/DrawEngineCommon.cpp:614
    #1 0x563fa635ce58 in DrawEngineCommon::ComputeMiniHash() ../GPU/Common/DrawEngineCommon.cpp:638
    #2 0x563fa67404cc in DrawEngineVulkan::DoFlush() ../GPU/Vulkan/DrawEngineVulkan.cpp:655
    #3 0x563fa6281151 in DrawEngineVulkan::Flush() ../GPU/Vulkan/DrawEngineVulkan.h:149
    #4 0x563fa674c366 in DrawEngineVulkan::DispatchFlush() ../GPU/Vulkan/DrawEngineVulkan.h:161
    #5 0x563fa64c3628 in GPUCommon::FastRunLoop(DisplayList&) ../GPU/GPUCommon.cpp:1059
    #6 0x563fa64c2557 in GPUCommon::InterpretList(DisplayList&) ../GPU/GPUCommon.cpp:1005
    #7 0x563fa64c5b4f in GPUCommon::ProcessDLQueue() ../GPU/GPUCommon.cpp:1206
    #8 0x563fa64bfcf0 in GPUCommon::EnqueueList(unsigned int, unsigned int, int, PSPPointer<PspGeListArgs>, bool) ../GPU/GPUCommon.cpp:800
    #9 0x563fa5d6997c in sceGeListEnQueue(unsigned int, unsigned int, int, unsigned int) ../Core/HLE/sceGe.cpp:342
    #10 0x563fa5d6f2ad in void WrapU_UUIU<&(sceGeListEnQueue(unsigned int, unsigned int, int, unsigned int))>() ../Core/HLE/FunctionWrappers.h:683
    #11 0x563fa5cf0548 in CallSyscallWithoutFlags(HLEFunction const*) ../Core/HLE/HLE.cpp:652
    #12 0x563f876fe630  (<unknown module>)
```

**Comment by hrydgard** [comment]
Oh, this one is a bit interesting. I'll fix it.
