### ISSUE TITLE
[UBSAN] StereoResampler: left shift of negative value

### ISSUE THREAD

**Issue by glebm** [hrydgard/ppsspp#14020]
```
../Core/HW/StereoResampler.cpp:226:22: runtime error: left shift of negative value -415
    #0 0x560f1440de61 in StereoResampler::Mix(short*, unsigned int, bool, int) ../Core/HW/StereoResampler.cpp:226
    #1 0x560f1405061b in __AudioMix(short*, int, int) ../Core/HLE/__sceAudio.cpp:468
    #2 0x560f13c09708 in NativeMix(short*, int) ../UI/NativeApp.cpp:274
    #3 0x560f14f36776 in sdl_mixaudio_callback(void*, unsigned char*, int) ../SDL/SDLMain.cpp:87
    #4 0x7f26b64c369e  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x2769e)
    #5 0x7f26b6524fcf  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x88fcf)
    #6 0x7f26b659cf4c  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x100f4c)
    #7 0x7f26b3a4358f in start_thread nptl/pthread_create.c:463
    #8 0x7f26b3969222 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x119222)

../Core/HW/StereoResampler.cpp:225:22: runtime error: left shift of negative value -145
    #0 0x560f1440ddab in StereoResampler::Mix(short*, unsigned int, bool, int) ../Core/HW/StereoResampler.cpp:225
    #1 0x560f1405061b in __AudioMix(short*, int, int) ../Core/HLE/__sceAudio.cpp:468
    #2 0x560f13c09708 in NativeMix(short*, int) ../UI/NativeApp.cpp:274
    #3 0x560f14f36776 in sdl_mixaudio_callback(void*, unsigned char*, int) ../SDL/SDLMain.cpp:87
    #4 0x7f26b64c369e  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x2769e)
    #5 0x7f26b6524fcf  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x88fcf)
    #6 0x7f26b659cf4c  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x100f4c)
    #7 0x7f26b3a4358f in start_thread nptl/pthread_create.c:463
    #8 0x7f26b3969222 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x119222)
```

**Comment by unknownbrackets** [comment]
If we don't mind changing the rounding bias from round toward negative infinity to round toward zero, we could skip the left shift entirely.  Since this is magnitude, that would seem more fair?

-[Unknown]

**Comment by hrydgard** [comment]
Should be fine, yeah..

**Comment by orbea** [comment]
@glebm and @unknownbrackets Was this fixed in PR https://github.com/hrydgard/ppsspp/pull/14040?

**Comment by unknownbrackets** [comment]
Should be.

-[Unknown]
