### ISSUE TITLE
(Android)(User Interface) Slow To Exit On Game Took 5 Seconds...

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14658]
### logs
[logs-2021-07-29-15-15-58.zip](https://github.com/hrydgard/ppsspp/files/6898657/logs-2021-07-29-15-15-58.zip)
### phone
Redmi Note 9 Android 10
Helio G85 Mali-G52 MC2 GPU
### ppsspp
v1.11.975 buildbot apk

**Comment by unknownbrackets** [comment]
How did you exit?  I don't really see any errors in the log.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Just clicking the exit text on ppsspp
This is mostly happen on 3D gfx games like Star Wars The Force Unleashed and SSX tour.

**Comment by Gamemulatorer** [comment]
This is also happen after hang
![Uploading Screenshot_2021-08-03-16-35-12-236_org.ppsspp.ppsspp.jpg…]()

**Comment by Gamemulatorer** [comment]
![Screenshot_2021-08-03-16-35-12-236_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/127985611-26ce5377-22e0-4bfb-a45c-3978024d62e7.jpg)
That also happen after hang and then load the game

**Comment by Gamemulatorer** [comment]
[ppsspp_screenrecord.zip](https://github.com/hrydgard/ppsspp/files/6981283/ppsspp_screenrecord.zip)
Still hang for 5 seconds after click the exit.

**Comment by Gamemulatorer** [comment]
08-29 23:55:30.205 1377:1822 I/WindowManager]
Relayout Window{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}: oldVis=4 newVis=0 focusMayChange = true

[08-29 23:55:30.209 1377:1822 W/WindowManager]
Changing focus fromnull to Window{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6048 com.android.server.wm.WindowManagerService.relayoutWindow:2627 com.android.server.wm.Session.relayout:213 

[08-29 23:55:30.211 1377:1822 D/WindowManager]
Input focus has changed to Window{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}

[08-29 23:55:30.580 1377:1397 I/Timeline]
Timeline: Activity_windows_visible id: ActivityRecord{1839573 u0 org.ppsspp.ppsspp/.PpssppActivity t707} time:116169515

[08-29 23:55:31.019 1377:5953 W/WindowManager]
Changing focus fromWindow{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} to Window{d3eaecf mode=1 rootTaskId=1 u0 Accessibility menu} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6048 com.android.server.wm.WindowManagerService.addWindow:1917 com.android.server.wm.Session.addToDisplayAsUser:176 

[08-29 23:55:31.052 1377:5498 W/WindowManager]
Changing focus fromWindow{d3eaecf mode=1 rootTaskId=1 u0 Accessibility menu} to Window{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6048 com.android.server.wm.WindowManagerService.relayoutWindow:2627 com.android.server.wm.Session.relayout:213 

[08-29 23:55:31.054 1377:5498 D/WindowManager]
Input focus has changed to Window{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}

[08-29 23:57:46.862 1377:1822 W/WindowManager]
Changing focus fromWindow{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} to Window{d053f9 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6048 com.android.server.wm.WindowManagerService.addWindow:1917 com.android.server.wm.Session.addToDisplayAsUser:176 

[08-29 23:57:46.865 1377:1822 D/WindowManager]
Input focus has changed to Window{d053f9 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}

[08-29 23:57:46.897 1377:1865 V/WindowManager]
Orientation start waiting for draw, mDrawState=DRAW_PENDING in Window{d053f9 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}, surfaceController Surface(name=org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity)/@0x3b936b5

[08-29 23:57:48.144 1377:3094 W/WindowManager]
Changing focus fromWindow{d053f9 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity EXITING} to Window{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6048 com.android.server.wm.WindowState.setupWindowForRemoveOnExit:2438 com.android.server.wm.WindowState.removeIfPossible:2407 

[08-29 23:57:48.146 1377:3094 D/WindowManager]
Input focus has changed to Window{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}

[08-30 00:00:39.223 1377:3056 W/WindowManager]
Changing focus fromWindow{48df286 mode=1 rootTaskId=707 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6048 com.android.server.wm.DisplayContent.setFocusedApp:5749 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:5716 

[08-30 00:00:39.653 13526:13526 W/Activity]
Slow Operation: Activity org.ppsspp.ppsspp/.PpssppActivity onPause took 397ms

[08-30 00:00:40.523 13526:13526 W/Activity]
Slow Operation: Activity org.ppsspp.ppsspp/.PpssppActivity onDestroy took 346ms

[08-30 00:00:40.529 1377:6497 D/WindowManager]
removeChild,stack:Task{681dc30 #707 visible=true type=standard mode=fullscreen translucent=true A=10514:org.ppsspp.ppsspp U=0 StackId=707 sz=0}
java.lang.Throwable
	at com.android.server.wm.TaskDisplayArea.removeChild(TaskDisplayArea.java:325)
	at com.android.server.wm.TaskDisplayArea.removeChild(TaskDisplayArea.java:82)
	at com.android.server.wm.WindowContainer.removeImmediately(WindowContainer.java:624)
	at com.android.server.wm.Task.removeImmediately(Task.java:2963)
	at com.android.server.wm.Task.removeIfPossible(Task.java:670)
	at com.android.server.wm.Task.removeChild(Task.java:1546)
	at com.android.server.wm.Task.removeChild(Task.java:1495)
	at com.android.server.wm.WindowContainer.removeImmediately(WindowContainer.java:624)
	at com.android.server.wm.WindowToken.removeImmediately(WindowToken.java:403)
	at com.android.server.wm.ActivityRecord.removeImmediately(ActivityRecord.java:3444)
	at com.android.server.wm.ActivityRecord.removeIfPossible(ActivityRecord.java:3451)
	at com.android.server.wm.ActivityRecord.onRemovedFromDisplay(ActivityRecord.java:3524)
	at com.android.server.wm.DisplayContent.removeAppToken(DisplayContent.java:1331)
	at com.android.server.wm.ActivityRecord.removeAppTokenFromDisplay(ActivityRecord.java:2218)
	at com.android.server.wm.ActivityRecord.removeFromHistory(ActivityRecord.java:3247)
	at com.android.server.wm.ActivityRecord.destroyed(ActivityRecord.java:3279)
	at com.android.server.wm.ActivityTaskManagerService.activityDestroyed(ActivityTaskManagerService.java:2003)
	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:2070)
	at android.os.Binder.execTransactInternal(Binder.java:1159)
	at android.os.Binder.execTransact(Binder.java:1123)

**Comment by Gamemulatorer** [comment]
Still slow on exit took 5 seconds
Hope the logs above can help.

**Comment by Gamemulatorer** [comment]
Cannot reproduce on my ancient phone.

**Comment by unknownbrackets** [comment]
Glad to hear - maybe it was related to some of our scoped storage changes (some made things faster for slow storage, even if it wasn't scoped storage.)  There are a few things that could've been taking time at shutdown.

-[Unknown]
