### ISSUE TITLE
Help android studio build crash on startup

### ISSUE THREAD

**Issue by ekorian26** [hrydgard/ppsspp#18886]
### Game or games this happens in

All 

### What area of the game / PPSSPP

Start

### What should happen

Not force close

### Logs

---------------------------- PROCESS STARTED (21795) for package org.ppsspp.ppsspp ----------------------------
2024-02-24 17:16:27.204 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  Setting requested rotation: 5 ('5') (Initialize)
2024-02-24 17:16:27.392 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  OpenGL ES 3.0 detected.
2024-02-24 17:16:27.414 21795-21795 InfraredHelper          org.ppsspp.ppsspp                    D  HasIrEmitter: false
2024-02-24 17:16:27.415 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  InfraredHelper exception: java.lang.Exception: No Ir Emitter
2024-02-24 17:16:27.415 21795-21795 BufferQueueConsumer     org.ppsspp.ppsspp                    I  [](id:552300000000,api:0,p:-1,c:21795) connect(): controlledByApp=true
2024-02-24 17:16:27.415 21795-21795 libMEOW                 org.ppsspp.ppsspp                    D  applied 1 plugins for [org.ppsspp.ppsspp]:
2024-02-24 17:16:27.415 21795-21795 libMEOW                 org.ppsspp.ppsspp                    D    plugin 1: [libMEOW_gift.so]:
2024-02-24 17:16:27.421 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  Setting requested rotation: 5 ('5') (onCreate)
2024-02-24 17:16:27.426 21795-21795 AudioManager            org.ppsspp.ppsspp                    W  Use of stream types is deprecated for operations other than volume control
2024-02-24 17:16:27.426 21795-21795 AudioManager            org.ppsspp.ppsspp                    W  See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2024-02-24 17:16:27.436 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    E  updateSystemUiVisibility: decor view not yet created, ignoring for now
2024-02-24 17:16:27.436 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    D  checkDisplayMeasurements: checking now
2024-02-24 17:16:27.441 21795-21795 SurfaceFactory          org.ppsspp.ppsspp                    I  [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@410d237
2024-02-24 17:16:27.441 21795-21795 libc                    org.ppsspp.ppsspp                    E  Access denied finding property "ro.vendor.tgpa_resolution_tuner"
2024-02-24 17:16:27.442 21795-21795 NativeSurfaceView       org.ppsspp.ppsspp                    I  NativeSurfaceView
2024-02-24 17:16:27.453 21795-21795 MogaHack                org.ppsspp.ppsspp                    E  MOGA
                                                                                                    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:437)
                                                                                                    	at org.ppsspp.ppsspp.MogaHack.init(MogaHack.java:75)
                                                                                                    	at org.ppsspp.ppsspp.NativeSurfaceView.<init>(NativeSurfaceView.java:51)
                                                                                                    	at org.ppsspp.ppsspp.NativeActivity.onCreate(NativeActivity.java:657)
                                                                                                    	at org.ppsspp.ppsspp.PpssppActivity.onCreate(PpssppActivity.java:130)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8077)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8061)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1315)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3607)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3879)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2203)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:268)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8019)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
2024-02-24 17:16:27.453 21795-21795 NativeSurfaceView       org.ppsspp.ppsspp                    I  MOGA initialized
2024-02-24 17:16:27.453 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  setcontentview before
2024-02-24 17:16:27.454 21795-21795 AppTurboService         org.ppsspp.ppsspp                    D  initialize
2024-02-24 17:16:27.455 21795-21795 AppTurboService         org.ppsspp.ppsspp                    D   mAppTurboTouchSlop = 0 mIsTpTurboApp = false
2024-02-24 17:16:27.455 21795-21795 AppTurboService         org.ppsspp.ppsspp                    D   getSettingSupport resullt = true mSettingCloudEnable = true
2024-02-24 17:16:27.456 21795-21795 AppTurboService         org.ppsspp.ppsspp                    D  YvelocityContentObserver new : super null
2024-02-24 17:16:27.462 21795-21795 AppTurboService         org.ppsspp.ppsspp                    D  versionName 1.17.1-19-dirty
2024-02-24 17:16:27.463 21795-21795 os.SingleLice           org.ppsspp.ppsspp                    D  instance successfully. com.transsion.scrollshot.v1.ScrollShotImplLice@205650d from com.transsion.scrollshot.ScrollShotImplLiceFactory
2024-02-24 17:16:27.463 21795-21795 os.SingleLiceFactory    org.ppsspp.ppsspp                    D  instance successfully. com.transsion.scrollshot.v1.ScrollShotImplLice@205650d from android.view.IViewLice
2024-02-24 17:16:27.463 21795-21795 os.LiceInfo             org.ppsspp.ppsspp                    D  instance successfully. com.transsion.view.ViewLice@6242cc2 from android.view.IViewLice
2024-02-24 17:16:27.471 21795-21795 os.SingleLice           org.ppsspp.ppsspp                    D  instance successfully. com.transsion.freeform.v1.FreeformLice@a304509 from com.transsion.freeform.FreeformLiceFactory
2024-02-24 17:16:27.472 21795-21795 os.SingleLiceFactory    org.ppsspp.ppsspp                    D  instance successfully. com.transsion.freeform.v1.FreeformLice@a304509 from com.android.internal.IInternalViewLice
2024-02-24 17:16:27.472 21795-21795 os.SingleLice           org.ppsspp.ppsspp                    D  instance successfully. com.transsion.whitenavigation.v1.WhiteNavigationLice@98c530e from com.transsion.whitenavigation.WhiteNavigationLiceFactory
2024-02-24 17:16:27.472 21795-21795 os.SingleLiceFactory    org.ppsspp.ppsspp                    D  instance successfully. com.transsion.whitenavigation.v1.WhiteNavigationLice@98c530e from com.android.internal.IInternalViewLice
2024-02-24 17:16:27.472 21795-21795 os.LiceInfo             org.ppsspp.ppsspp                    D  instance successfully. com.transsion.internal.InternalViewLice@ce1d12f from com.android.internal.IInternalViewLice
2024-02-24 17:16:27.474 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  setcontentview after
2024-02-24 17:16:27.474 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    W  startRenderLoopThread - not starting thread, needs surface
2024-02-24 17:16:27.479 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    D  checkDisplayMeasurements: checking now
2024-02-24 17:16:27.480 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  Setting requested rotation: 5 ('5') (onResume)
2024-02-24 17:16:27.480 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  onResume
2024-02-24 17:16:27.488 21795-21795 AudioManager            org.ppsspp.ppsspp                    W  Use of stream types is deprecated for operations other than volume control
2024-02-24 17:16:27.488 21795-21795 AudioManager            org.ppsspp.ppsspp                    W  See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2024-02-24 17:16:27.497 21795-21890 ActivityThreadLice      org.ppsspp.ppsspp                    D  received OSMessage 110001
2024-02-24 17:16:27.498 21795-21890 ActivityThreadLice      org.ppsspp.ppsspp                    D  send OSMessage 110001 to [-1]
2024-02-24 17:16:27.500 21795-21795 g.ppsspp.ppssp          org.ppsspp.ppsspp                    D  PlayerBase::PlayerBase()
2024-02-24 17:16:27.500 21795-21795 g.ppsspp.ppssp          org.ppsspp.ppsspp                    D  TrackPlayerBase::TrackPlayerBase()
2024-02-24 17:16:27.500 21795-21795 libOpenSLES             org.ppsspp.ppsspp                    I  Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
2024-02-24 17:16:27.500 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  INSP: type=audio,case=1,set=0xb400007394ea9c40,stream_type=3,sample_rate=48000,format=0x1,channel_mask=0x3,frame_count=0,flags=0x104,notification_frames=-2,session_id=1433,transfer_type=0,uid=-1,pid=-1
2024-02-24 17:16:27.501 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  set(): 0xb400007394ea9c40, Create AudioTrackThread, tid = 21899
2024-02-24 17:16:27.511 21795-21890 OSServiceManager        org.ppsspp.ppsspp                    D  update local os service os.activity from null to android.os.BinderProxy@5dda728
2024-02-24 17:16:27.519 21795-21795 AudioTrack              org.ppsspp.ppsspp                    I  createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 768
2024-02-24 17:16:27.520 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  createTrack_l(194): 0xb400007394ea9c40, mCblk = 0x7207e14000, mLatency = 58, mAfLatency = 42, frameCount = 768, mSampleRate = 48000, mFlags = 0x4, mReqFrameCount = 768, mNotificationFramesAct = 256
2024-02-24 17:16:27.522 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  start(194): 0xb400007394ea9c40, prior state:STATE_STOPPED
2024-02-24 17:16:27.525 21795-21899 g.ppsspp.ppssp          org.ppsspp.ppsspp                    D  PlayerBase::stop() from IPlayer
2024-02-24 17:16:27.525 21795-21899 AudioTrack              org.ppsspp.ppsspp                    D  stop(194): 0xb400007394ea9c40, prior state:STATE_ACTIVE
2024-02-24 17:16:27.525 21795-21899 AudioTrack              org.ppsspp.ppsspp                    D  stop(194): called with 0 frames delivered
2024-02-24 17:16:27.528 21795-21899 AudioTrack              org.ppsspp.ppsspp                    D  stop(194): 0xb400007394ea9c40 stop done
2024-02-24 17:16:27.528 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  start(194): 0xb400007394ea9c40, prior state:STATE_STOPPED
2024-02-24 17:16:27.528 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    W  startRenderLoopThread - not starting thread, needs surface
2024-02-24 17:16:27.539 21795-21795 libc                    org.ppsspp.ppsspp                    E  Access denied finding property "ro.vendor.scaler_version"
2024-02-24 17:16:27.542 21795-21795 libc                    org.ppsspp.ppsspp                    E  Access denied finding property "ro.vendor.scaler_version"
2024-02-24 17:16:27.545 21795-21795 ViewRootIm...pActivity] org.ppsspp.ppsspp                    D  hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2024-02-24 17:16:27.549 21795-21795 InputTransport          org.ppsspp.ppsspp                    I  Create ARC handle: 0xb4000072b4f07640
2024-02-24 17:16:27.549 21795-21795 InputTransport          org.ppsspp.ppsspp                    I  InputConsumer create TRAN_APPTURBO_ENABLE disable
2024-02-24 17:16:27.549 21795-21795 PhoneWindow             org.ppsspp.ppsspp                    V  DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@afa0dd4, this = DecorView@2a6ab7d[PpssppActivity]
2024-02-24 17:16:27.553 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  onPause
2024-02-24 17:16:27.556 21795-21795 g.ppsspp.ppssp          org.ppsspp.ppsspp                    D  PlayerBase::stop() from IPlayer
2024-02-24 17:16:27.556 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  stop(194): 0xb400007394ea9c40, prior state:STATE_ACTIVE
2024-02-24 17:16:27.556 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  stop(194): called with 768 frames delivered
2024-02-24 17:16:27.556 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  stop(194): 0xb400007394ea9c40 stop done
2024-02-24 17:16:27.556 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  stop(194): 0xb400007394ea9c40, prior state:STATE_STOPPED
2024-02-24 17:16:27.556 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  ~AudioTrack(194): 0xb400007394ea9c40
2024-02-24 17:16:27.556 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  stop(194): 0xb400007394ea9c40, prior state:STATE_STOPPED
2024-02-24 17:16:27.559 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  Joining render thread...
2024-02-24 17:16:27.559 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  requestExitVulkanRenderLoop
2024-02-24 17:16:27.559 21795-21795 PPSSPP                  org.ppsspp.ppsspp                    E  [SYSTEM] Render loop already exited
2024-02-24 17:16:27.559 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  Joined render thread
2024-02-24 17:16:27.559 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  onPause completed
2024-02-24 17:16:27.559 21795-21795 ActivityThread          org.ppsspp.ppsspp                    D  -- comp:org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity
2024-02-24 17:16:27.559 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  onDestroy
2024-02-24 17:16:27.560 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  onDestroy
2024-02-24 17:16:27.561 21795-21795 View                    org.ppsspp.ppsspp                    D  [Warning] assignParent to null: this = DecorView@2a6ab7d[PpssppActivity]
2024-02-24 17:16:27.564 21795-21795 InputTransport          org.ppsspp.ppsspp                    I  Destroy ARC handle: 0xb4000072b4f07640
2024-02-24 17:16:27.569 21795-21795 ActivityThread          org.ppsspp.ppsspp                    D  ++ activityComponent:org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity counts:1
2024-02-24 17:16:27.569 21795-21795 AppTurboService         org.ppsspp.ppsspp                    D  AppTurboService.initializeAppTurboFactory()
2024-02-24 17:16:27.574 21795-21795 TextRenderer            org.ppsspp.ppsspp                    I  Successfully loaded Roboto Condensed
2024-02-24 17:16:27.577 21795-21902 libMEOW                 org.ppsspp.ppsspp                    D  applied 1 plugins for [org.ppsspp.ppsspp]:
2024-02-24 17:16:27.577 21795-21902 libMEOW                 org.ppsspp.ppsspp                    D    plugin 1: [libMEOW_gift.so]:
2024-02-24 17:16:27.587 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  Setting requested rotation: 5 ('5') (onCreate)
2024-02-24 17:16:27.587 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    E  updateSystemUiVisibility: decor view not yet created, ignoring for now
2024-02-24 17:16:27.587 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    D  checkDisplayMeasurements: checking now
2024-02-24 17:16:27.588 21795-21795 NativeSurfaceView       org.ppsspp.ppsspp                    I  NativeSurfaceView
2024-02-24 17:16:27.593 21795-21795 MogaHack                org.ppsspp.ppsspp                    E  MOGA
                                                                                                    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:437)
                                                                                                    	at org.ppsspp.ppsspp.MogaHack.init(MogaHack.java:75)
                                                                                                    	at org.ppsspp.ppsspp.NativeSurfaceView.<init>(NativeSurfaceView.java:51)
                                                                                                    	at org.ppsspp.ppsspp.NativeActivity.onCreate(NativeActivity.java:657)
                                                                                                    	at org.ppsspp.ppsspp.PpssppActivity.onCreate(PpssppActivity.java:130)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8077)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8061)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1315)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3607)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3879)
                                                                                                    	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5780)
                                                                                                    	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5686)
                                                                                                    	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2203)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:268)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8019)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
2024-02-24 17:16:27.593 21795-21795 NativeSurfaceView       org.ppsspp.ppsspp                    I  MOGA initialized
2024-02-24 17:16:27.593 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  setcontentview before
2024-02-24 17:16:27.595 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  setcontentview after
2024-02-24 17:16:27.595 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    W  startRenderLoopThread - not starting thread, needs surface
2024-02-24 17:16:27.598 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    D  checkDisplayMeasurements: checking now
2024-02-24 17:16:27.598 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  Setting requested rotation: 5 ('5') (onResume)
2024-02-24 17:16:27.599 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  onResume
2024-02-24 17:16:27.606 21795-21795 g.ppsspp.ppssp          org.ppsspp.ppsspp                    D  PlayerBase::PlayerBase()
2024-02-24 17:16:27.607 21795-21795 g.ppsspp.ppssp          org.ppsspp.ppsspp                    D  TrackPlayerBase::TrackPlayerBase()
2024-02-24 17:16:27.607 21795-21795 libOpenSLES             org.ppsspp.ppsspp                    I  Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
2024-02-24 17:16:27.607 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  INSP: type=audio,case=1,set=0xb400007394eb10b0,stream_type=3,sample_rate=48000,format=0x1,channel_mask=0x3,frame_count=0,flags=0x104,notification_frames=-2,session_id=1441,transfer_type=0,uid=-1,pid=-1
2024-02-24 17:16:27.607 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  set(): 0xb400007394eb10b0, Create AudioTrackThread, tid = 21904
2024-02-24 17:16:27.656 21795-21795 AudioTrack              org.ppsspp.ppsspp                    I  createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 768
2024-02-24 17:16:27.657 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  createTrack_l(195): 0xb400007394eb10b0, mCblk = 0x7207e150e0, mLatency = 58, mAfLatency = 42, frameCount = 768, mSampleRate = 48000, mFlags = 0x4, mReqFrameCount = 768, mNotificationFramesAct = 256
2024-02-24 17:16:27.658 21795-21795 AudioTrack              org.ppsspp.ppsspp                    D  start(195): 0xb400007394eb10b0, prior state:STATE_STOPPED
2024-02-24 17:16:27.659 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    W  startRenderLoopThread - not starting thread, needs surface
2024-02-24 17:16:27.659 21795-21795 PhoneWindow             org.ppsspp.ppsspp                    V  DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@3b6496[]
2024-02-24 17:16:27.661 21795-21795 ViewRootIm...pActivity] org.ppsspp.ppsspp                    D  hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2024-02-24 17:16:27.666 21795-21795 InputTransport          org.ppsspp.ppsspp                    I  Create ARC handle: 0xb4000072b4f07cd0
2024-02-24 17:16:27.666 21795-21795 InputTransport          org.ppsspp.ppsspp                    I  InputConsumer create TRAN_APPTURBO_ENABLE disable
2024-02-24 17:16:27.666 21795-21795 PhoneWindow             org.ppsspp.ppsspp                    V  DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@c1e6ded, this = DecorView@3b6496[PpssppActivity]
2024-02-24 17:16:27.667 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  onAttachedToWindow
2024-02-24 17:16:27.668 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    I  Safe insets: left: 108 right: 0 top: 0 bottom: 0
2024-02-24 17:16:27.681 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    I  Safe insets: left: 108 right: 0 top: 0 bottom: 0
2024-02-24 17:16:27.683 21795-21845 libMEOW                 org.ppsspp.ppsspp                    D  applied 1 plugins for [org.ppsspp.ppsspp]:
2024-02-24 17:16:27.683 21795-21845 libMEOW                 org.ppsspp.ppsspp                    D    plugin 1: [libMEOW_gift.so]:
2024-02-24 17:16:27.691 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    I  Correct orientation detected, resetting orientation counter.
2024-02-24 17:16:27.692 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    D  Surface created. pixelWidth=2460, pixelHeight=1080 holder: android.view.SurfaceView$2@c13422 or: 6 90.0Hz
2024-02-24 17:16:27.692 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    D  Setting fixed size 0 x 0
2024-02-24 17:16:27.692 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    V  surfaceChanged: isCreating:true holder: android.view.SurfaceView$2@c13422
2024-02-24 17:16:27.692 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    W  Surface changed. Resolution: 2460x1080 Format: 4
2024-02-24 17:16:27.692 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    W  startRenderLoopThread: Starting thread
2024-02-24 17:16:27.692 21795-21795 PPSSPPNativeActivity    org.ppsspp.ppsspp                    I  Setting desired framerate to 60.0 Hz method=1
2024-02-24 17:16:27.696 21795-21845 GED                     org.ppsspp.ppsspp                    I  [GT]_get_procNameprocess pid(21795)
2024-02-24 17:16:27.696 21795-21845 GED                     org.ppsspp.ppsspp                    I  [GT]_getprocess name(org.ppsspp.ppsspp)
2024-02-24 17:16:27.696 21795-21845 g.ppsspp.ppssp          org.ppsspp.ppsspp                    I  [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
2024-02-24 17:16:27.696 21795-21845 libMEOW_gift            org.ppsspp.ppsspp                    I  ctx:0xb4000073e4f8beb8, ARC not Enabled.
2024-02-24 17:16:27.724 21795-21918 ion                     org.ppsspp.ppsspp                    E  ioctl c0044901 failed with code -1: Invalid argument
2024-02-24 17:16:27.797 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    I  SystemUiVisibilityChange! visibility=7 navigationHidden: true
2024-02-24 17:16:27.797 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    I  decorView: 2460x1080
2024-02-24 17:16:27.797 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    D  checkDisplayMeasurements: checking now
2024-02-24 17:16:27.819 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    I  Safe insets: left: 108 right: 0 top: 0 bottom: 0
2024-02-24 17:16:27.924 21795-21795 PPSSPPSizeManager       org.ppsspp.ppsspp                    D  checkDisplayMeasurements: checking now
2024-02-24 17:16:30.200 21795-21838 g.ppsspp.ppssp          org.ppsspp.ppsspp                    D  TrackPlayerBase::~TrackPlayerBase()
2024-02-24 17:16:30.200 21795-21838 g.ppsspp.ppssp          org.ppsspp.ppsspp                    D  PlayerBase::~PlayerBase()
2024-02-24 17:16:31.970 21795-21918 libc                    org.ppsspp.ppsspp                    A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc in tid 21918 (EmuThread), pid 21795 (androidInit)
---------------------------- PROCESS STARTED (21949) for package org.ppsspp.ppsspp ----------------------------
---------------------------- PROCESS ENDED (21795) for package org.ppsspp.ppsspp ----------------------------
---------------------------- PROCESS ENDED (21949) for package org.ppsspp.ppsspp ----------------------------

### Platform

Android

### Mobile device model or graphics card (GPU)

Infinix note 10 pro

### PPSSPP version affected

v1.17.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Fix coming soon.
