### ISSUE TITLE
SDL on ARM GLES Segfault

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#7815]
I managed to compile 1.0.1 SDL on ARM GLES hardware (odroid U3), with this:

cmake . -DUSING_GLES2=ON
(and find_package(X11) in CMakeLists.txt, it's missing btw...)

but it's trying to use /usr/lib/arm-linux-gnueabihf/mesa/libGL.so.1 instead /usr/lib/arm-linux-gnueabihf/libGLESv2.so (which is symlink to Mali lib)
What am I missing here?

```
ppsspp 
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: dlopen /usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen ${ORIGIN}/dri/exynos_dri.so failed (${ORIGIN}/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen /usr/lib/dri/exynos_dri.so failed (/usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: exynos_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: exynos
ERROR: EGL Error detected in file /home/odroid/Projects/PPSSPP/ppsspp-1.0.1/native/base/PCMain.cpp at line 170: EGL_BAD_NATIVE_WINDOW (0x300B)
EGL ERROR: Unable to create EGL surface!
04:11:049 Core/Config.cpp:843 I[LOAD]: Loading controller config: /home/odroid/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 1360 x 768
Virtual pixels: 1360 x 768
I: /home/odroid/Projects/PPSSPP/ppsspp-1.0.1/native/thin3d/thin3d_gl.cpp:229: I: Vertex Shader compile error:

I: /home/odroid/Projects/PPSSPP/ppsspp-1.0.1/native/thin3d/thin3d_gl.cpp:229: I: Vertex Shader compile error:

I: /home/odroid/Projects/PPSSPP/ppsspp-1.0.1/native/thin3d/thin3d_gl.cpp:229: I: Fragment Shader compile error:

I: /home/odroid/Projects/PPSSPP/ppsspp-1.0.1/native/thin3d/thin3d_gl.cpp:229: I: Fragment Shader compile error:

E: /home/odroid/Projects/PPSSPP/ppsspp-1.0.1/native/thin3d/thin3d_gl.cpp:557: E: ShaderSet requires both a valid vertex and a fragment shader: (nil) (nil)
E: /home/odroid/Projects/PPSSPP/ppsspp-1.0.1/native/thin3d/thin3d_gl.cpp:557: E: ShaderSet requires both a valid vertex and a fragment shader: (nil) (nil)
I: /home/odroid/Projects/PPSSPP/ppsspp-1.0.1/native/gfx_es2/gl_state.cpp:133: I: GPU Vendor : (null) ; renderer: N/A version str: N/A ; GLSL version str: N/A
Segmentation fault
```

```
(gdb) bt full
#0  __GI_strstr (haystack_start=0x0, needle_start=0x80ce1c "3.0") at strstr.c:63
        haystack = <optimized out>
        needle = <optimized out>
        needle_len = <optimized out>
        haystack_len = <optimized out>
        ok = true
#1  0x00509a1e in CheckGLExtensions() ()
No symbol table info available.
#2  0x000fbfe6 in NativeInitGraphics() ()
No symbol table info available.
#3  0x000f8b24 in main ()
No symbol table info available.
```

```
ldd /usr/games/ppsspp 
    libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6ef2000)
    libEGL.so => /usr/lib/arm-linux-gnueabihf/libEGL.so (0xb6e1f000)
    libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb6e04000)
    librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6df6000)
    libX11.so.6 => /usr/lib/arm-linux-gnueabihf/libX11.so.6 (0xb6d10000)
    libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6d05000)
    libSDL2-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libSDL2-2.0.so.0 (0xb6c54000)
    libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6baa000)
    libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6b3e000)
    libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6b1d000)
    libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6a36000)
    /lib/ld-linux-armhf.so.3 (0xb6f34000)
    libdrm.so.2 => /usr/lib/arm-linux-gnueabihf/libdrm.so.2 (0xb6a25000)
    libXfixes.so.3 => /usr/lib/arm-linux-gnueabihf/libXfixes.so.3 (0xb6a19000)
    libXext.so.6 => /usr/lib/arm-linux-gnueabihf/libXext.so.6 (0xb6a07000)
    libxcb.so.1 => /usr/lib/arm-linux-gnueabihf/libxcb.so.1 (0xb69ed000)
    libasound.so.2 => /usr/lib/arm-linux-gnueabihf/libasound.so.2 (0xb6953000)
    libpulse-simple.so.0 => /usr/lib/arm-linux-gnueabihf/libpulse-simple.so.0 (0xb6947000)
    libpulse.so.0 => /usr/lib/arm-linux-gnueabihf/libpulse.so.0 (0xb690e000)
    libXcursor.so.1 => /usr/lib/arm-linux-gnueabihf/libXcursor.so.1 (0xb68ff000)
    libXinerama.so.1 => /usr/lib/arm-linux-gnueabihf/libXinerama.so.1 (0xb68f5000)
    libXi.so.6 => /usr/lib/arm-linux-gnueabihf/libXi.so.6 (0xb68e3000)
    libXrandr.so.2 => /usr/lib/arm-linux-gnueabihf/libXrandr.so.2 (0xb68d4000)
    libXss.so.1 => /usr/lib/arm-linux-gnueabihf/libXss.so.1 (0xb68c9000)
    libXxf86vm.so.1 => /usr/lib/arm-linux-gnueabihf/libXxf86vm.so.1 (0xb68bd000)
    libwayland-egl.so.1 => /usr/lib/arm-linux-gnueabihf/libwayland-egl.so.1 (0xb68b3000)
    libwayland-client.so.0 => /usr/lib/arm-linux-gnueabihf/libwayland-client.so.0 (0xb68a3000)
    libwayland-cursor.so.0 => /usr/lib/arm-linux-gnueabihf/libwayland-cursor.so.0 (0xb6893000)
    libxkbcommon.so.0 => /usr/lib/arm-linux-gnueabihf/libxkbcommon.so.0 (0xb685f000)
    libXau.so.6 => /usr/lib/arm-linux-gnueabihf/libXau.so.6 (0xb6854000)
    libXdmcp.so.6 => /usr/lib/arm-linux-gnueabihf/libXdmcp.so.6 (0xb6848000)
    libpulsecommon-4.0.so => /usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsecommon-4.0.so (0xb67f9000)
    libjson-c.so.2 => /lib/arm-linux-gnueabihf/libjson-c.so.2 (0xb67ea000)
    libdbus-1.so.3 => /lib/arm-linux-gnueabihf/libdbus-1.so.3 (0xb67b9000)
    libXrender.so.1 => /usr/lib/arm-linux-gnueabihf/libXrender.so.1 (0xb67aa000)
    libffi.so.6 => /usr/lib/arm-linux-gnueabihf/libffi.so.6 (0xb679c000)
    libwrap.so.0 => /lib/arm-linux-gnueabihf/libwrap.so.0 (0xb678d000)
    libsndfile.so.1 => /usr/lib/arm-linux-gnueabihf/libsndfile.so.1 (0xb673c000)
    libasyncns.so.0 => /usr/lib/arm-linux-gnueabihf/libasyncns.so.0 (0xb6730000)
    libnsl.so.1 => /lib/arm-linux-gnueabihf/libnsl.so.1 (0xb6718000)
    libFLAC.so.8 => /usr/lib/arm-linux-gnueabihf/libFLAC.so.8 (0xb66ef000)
    libvorbisenc.so.2 => /usr/lib/arm-linux-gnueabihf/libvorbisenc.so.2 (0xb6581000)
    libvorbis.so.0 => /usr/lib/arm-linux-gnueabihf/libvorbis.so.0 (0xb6557000)
    libogg.so.0 => /usr/lib/arm-linux-gnueabihf/libogg.so.0 (0xb654a000)
    libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0xb6531000)
```

**Comment by sergiobenrocha2** [comment]
Same thing with the git version

**Comment by unknownbrackets** [comment]
Someone mentioned renaming exynos.conf:

http://forum.odroid.com/viewtopic.php?f=77&t=4628&p=37134#p37132

Anyway, this seems like a platform issue.

-[Unknown]

**Comment by sergiobenrocha2** [comment]
Still getting this issue in 1.5.3. Weird, I don't have that exynos.conf file here

```
ppsspp-sdl 
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: dlopen /usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen ${ORIGIN}/dri/exynos_dri.so failed (${ORIGIN}/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen /usr/lib/dri/exynos_dri.so failed (/usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: exynos_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: exynos
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/assets/lang/en_US.ini
W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/lang/en_US.ini
I: Config.cpp:437: Longest display side: -1 pixels. Choosing scale 1
21:30:286 Core/Config.cpp:1028 I[LOADER]: Loading controller config: /home/odroid/.config/ppsspp/PSP/SYSTEM/controls.ini
ERROR: EGL Error detected in file /build/ppsspp-R51upN/ppsspp-1.5.3-r201712041808-341611e/ext/native/base/PCMain.cpp at line 187: EGL_BAD_NATIVE_WINDOW (0x300B)
EGL ERROR: Unable to create EGL surface!
Pixels: 1360 x 768
Virtual pixels: 1360 x 768
I: gpu_features.cpp:136: GPU Vendor : (null) ; renderer: N/A version str: N/A ; GLSL version str: N/A
Segmentation fault
```

Yeah, maybe it's a platform issue. Anyone with another board to test?

**Comment by clort81** [comment]
> Still getting this issue in 1.5.3. Weird, I don't have that exynos.conf file here
> 
> ```
> ppsspp-sdl 
> libGL error: MESA-LOADER: malformed or no PCI ID
> libGL error: dlopen /usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
> libGL error: dlopen ${ORIGIN}/dri/exynos_dri.so failed (${ORIGIN}/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
> libGL error: dlopen /usr/lib/dri/exynos_dri.so failed (/usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
> libGL error: unable to load driver: exynos_dri.so
> libGL error: driver pointer missing
> libGL error: failed to load driver: exynos
> W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/assets/lang/en_US.ini
> W: file_util.cpp:175: IsDirectory: stat failed on /usr/games/lang/en_US.ini
> I: Config.cpp:437: Longest display side: -1 pixels. Choosing scale 1
> 21:30:286 Core/Config.cpp:1028 I[LOADER]: Loading controller config: /home/odroid/.config/ppsspp/PSP/SYSTEM/controls.ini
> ERROR: EGL Error detected in file /build/ppsspp-R51upN/ppsspp-1.5.3-r201712041808-341611e/ext/native/base/PCMain.cpp at line 187: EGL_BAD_NATIVE_WINDOW (0x300B)
> EGL ERROR: Unable to create EGL surface!
> Pixels: 1360 x 768
> Virtual pixels: 1360 x 768
> I: gpu_features.cpp:136: GPU Vendor : (null) ; renderer: N/A version str: N/A ; GLSL version str: N/A
> Segmentation fault
> ```
> 
> Yeah, maybe it's a platform issue. Anyone with another board to test?
I think it's related to your libSDL build - that will look for libGL if not configured for gles.  I think it will prefer gl to gles if both are present, and we want the opposite behavior, for arm systems with gl4es as backup.
