### ISSUE TITLE
Qt5 build segfault on ARM

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#7817]
I compiled with Qt5 support, and it's segfaulting:

```
./Qt/ppsspp 
55:56:845 Core/Config.cpp:870 I[LOAD]: Loading controller config: /home/odroid/.config/ppsspp/PSP/SYSTEM/controls.ini
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: dlopen /usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen ${ORIGIN}/dri/exynos_dri.so failed (${ORIGIN}/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen /usr/lib/dri/exynos_dri.so failed (/usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: exynos_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: exynos
E: ../native/base/QtMain.cpp:182: E: Output audio samples: 1024 (requested: 2048)
I: ../native/gfx_es2/gl_state.cpp:136: I: GPU Vendor : ARM ; renderer: Mali-400 MP version str: OpenGL ES 2.0 ; GLSL version str: OpenGL ES GLSL ES 1.00
I: ../native/gfx_es2/gpu_features.cpp:20: I: Checking for GL driver bugs... vendor=4 model='Mali-400 MP'
Segmentation fault
```

```
(gdb) run
Starting program: /home/odroid/Projects/PPSSPP/ppsspp-git/Qt/ppsspp 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/arm-linux-gnueabihf/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[New Thread 0xb35a5050 (LWP 11497)]
[New Thread 0xb2da5050 (LWP 11498)]
[New Thread 0xb15fb050 (LWP 11500)]
[New Thread 0xb0bff050 (LWP 11501)]
[New Thread 0xb01ff050 (LWP 11502)]
[New Thread 0xaf9ff050 (LWP 11503)]
53:23:527 Core/Config.cpp:870 I[LOAD]: Loading controller config: /home/odroid/.config/ppsspp/PSP/SYSTEM/controls.ini
[New Thread 0xaefff050 (LWP 11504)]
[Thread 0xaf9ff050 (LWP 11503) exited]
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: dlopen /usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen ${ORIGIN}/dri/exynos_dri.so failed (${ORIGIN}/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen /usr/lib/dri/exynos_dri.so failed (/usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: exynos_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: exynos
[New Thread 0xaf9ff050 (LWP 11505)]
[New Thread 0xaa31b050 (LWP 11506)]
[Thread 0xaa31b050 (LWP 11506) exited]
[New Thread 0xaa31b050 (LWP 11507)]
E: ../native/base/QtMain.cpp:182: E: Output audio samples: 1024 (requested: 2048)
I: ../native/gfx_es2/gl_state.cpp:136: I: GPU Vendor : ARM ; renderer: Mali-400 MP version str: OpenGL ES 2.0 ; GLSL version str: OpenGL ES GLSL ES 1.00
I: ../native/gfx_es2/gpu_features.cpp:20: I: Checking for GL driver bugs... vendor=4 model='Mali-400 MP'

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xaa31b050 (LWP 11507)]
PlayBackgroundAudio () at ../UI/BackgroundAudio.cpp:214
214     if (!at3Reader && bgGamePath.size() && (time_now_d() - gameLastChanged > 0.5)) {


(gdb) bt full
#0  PlayBackgroundAudio () at ../UI/BackgroundAudio.cpp:214
        lock = {mtx_ = @0xef0a38}
        now = <optimized out>
#1  0x0009ff7e in NativeMix (audio=0x1a37798, num_samples=1024) at ../UI/NativeApp.cpp:240
        sample_rate = <optimized out>
#2  0xb6e15492 in SDL_RunAudio (devicep=0x19a3f50) at /build/buildd/libsdl2-2.0.2+dfsg1/src/audio/SDL_audio.c:483
        silence = 0
        device = 0x19a3f50
        stream = 0x1a37798 ""
        stream_len = 4096
        udata = 0x0
        fill = 0x6611d <mixaudio(void*, unsigned char*, int)>
        delay = 23
#3  0xb6e5a5bc in SDL_RunThread (data=0x19a42d8) at /build/buildd/libsdl2-2.0.2+dfsg1/src/thread/SDL_thread.c:282
        args = 0x19a42d8
        userfunc = 0xb6e153a9 <SDL_RunAudio>
        userdata = 0x19a3f50
        thread = 0x19c7c18
        statusloc = 0x19c7c20
#4  0xb6e8f84a in RunThread (data=<optimized out>) at /build/buildd/libsdl2-2.0.2+dfsg1/src/thread/pthread/SDL_systhread.c:72
No locals.
#5  0xb6424fbc in start_thread (arg=0xaa31b050) at pthread_create.c:314
        pd = 0xaa31b050
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-1439583640, -1439584176, 1, -1439585720, -1439585392, -1237085796, -1439583612, -1090523800, -545593436, 
                -1022819723, 0 <repeats 54 times>}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0xb629420c in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92 from /lib/arm-linux-gnueabihf/libc.so.6
No locals.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Compile flags:

```
g++ -c -pipe -Wno-unused-function -Wno-unused-variable -Wno-strict-aliasing -fno-strict-aliasing -Wno-unused-parameter -Wno-multichar -Wno-uninitialized -Wno-ignored-qualifiers -Wno-missing-field-initializers -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -march=armv7-a -mtune=cortex-a8 -mfpu=neon -ftree-vectorize -O3 -ffast-math -fPIC -std=c++0x -Wall -W -D_REENTRANT -DUSING_QT_UI -DUSE_FFMPEG -DARM -D_ARCH_32 -DPPSSPP_GIT_VERSION="\"v1.0.1-602-gce4e593\"" -D__STDC_CONSTANT_MACROS -DUSING_GLES2 -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I. -I../Common -I../ffmpeg/linux/armv7/include -I../native -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I.moc/Common -o .obj/Common/Misc.o ../Common/Misc.cpp
```

Link flags:

```
g++ -Wl,-Bsymbolic-functions -Wl,-z,relro -o ppsspp .obj/ppsspp/SDLJoystick.o .obj/ppsspp/QtMain.o .obj/ppsspp/BackgroundAudio.o .obj/ppsspp/ControlMappingScreen.o .obj/ppsspp/CwCheatScreen.o .obj/ppsspp/DevScreens.o .obj/ppsspp/EmuScreen.o .obj/ppsspp/GameInfoCache.o .obj/ppsspp/GamepadEmu.o .obj/ppsspp/GameScreen.o .obj/ppsspp/GameSettingsScreen.o .obj/ppsspp/InstallZipScreen.o .obj/ppsspp/MainScreen.o .obj/ppsspp/MiscScreens.o .obj/ppsspp/NativeApp.o .obj/ppsspp/OnScreenDisplay.o .obj/ppsspp/PauseScreen.o .obj/ppsspp/ReportScreen.o .obj/ppsspp/SavedataScreen.o .obj/ppsspp/Store.o .obj/ppsspp/TiltAnalogSettingsScreen.o .obj/ppsspp/TiltEventProcessor.o .obj/ppsspp/TouchControlLayoutScreen.o .obj/ppsspp/TouchControlVisibilityScreen.o .obj/ppsspp/ui_atlas.o .obj/ppsspp/TestRunner.o .obj/ppsspp/mainwindow.o .obj/ppsspp/ctrldisasmview.o .obj/ppsspp/ctrlmemview.o .obj/ppsspp/ctrlregisterlist.o .obj/ppsspp/ctrlvfpuview.o .obj/ppsspp/debugger_disasm.o .obj/ppsspp/debugger_displaylist.o .obj/ppsspp/debugger_memory.o .obj/ppsspp/debugger_memorytex.o .obj/ppsspp/debugger_vfpu.o .obj/ppsspp/qrc_desktop_assets.o .obj/ppsspp/moc_QtMain.o .obj/ppsspp/moc_mainwindow.o .obj/ppsspp/moc_ctrldisasmview.o .obj/ppsspp/moc_ctrlmemview.o .obj/ppsspp/moc_ctrlregisterlist.o .obj/ppsspp/moc_ctrlvfpuview.o .obj/ppsspp/moc_debugger_disasm.o .obj/ppsspp/moc_debugger_displaylist.o .obj/ppsspp/moc_debugger_memory.o .obj/ppsspp/moc_debugger_memorytex.o .obj/ppsspp/moc_debugger_vfpu.o   -L/home/odroid/Projects/PPSSPP/ppsspp-git/Qt -L/home/odroid/Projects/PPSSPP/ppsspp-git/Qt/../ffmpeg/linux/armv7/lib/ -lCore -lGPU -lCommon -lNative -ldl -lrt -lavformat -lavcodec -lavutil -lswresample -lswscale -lEGL -lz -lSDL2 -lQt5OpenGL -L/usr/lib/arm-linux-gnueabihf -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread
```

Qt 5.2.1, gcc 4.8.4, Ubuntu 14.04, odroid U3.

Qt4 works. Qt5 works in desktop (tested only in amd64).

**Comment by sergiobenrocha2** [comment]
With 

[Sound]
Enable = False

in settings:

```
(gdb) run
Starting program: /home/odroid/Projects/PPSSPP/ppsspp-git/Qt/ppsspp 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/arm-linux-gnueabihf/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[New Thread 0xb35a5050 (LWP 11602)]
[New Thread 0xb2da5050 (LWP 11603)]
[New Thread 0xb15fb050 (LWP 11605)]
[New Thread 0xb0bff050 (LWP 11606)]
[New Thread 0xb01ff050 (LWP 11607)]
[New Thread 0xaf9ff050 (LWP 11608)]
06:23:516 Core/Config.cpp:870 I[LOAD]: Loading controller config: /home/odroid/.config/ppsspp/PSP/SYSTEM/controls.ini
[New Thread 0xaefff050 (LWP 11609)]
[Thread 0xaf9ff050 (LWP 11608) exited]
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: dlopen /usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen ${ORIGIN}/dri/exynos_dri.so failed (${ORIGIN}/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: dlopen /usr/lib/dri/exynos_dri.so failed (/usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: exynos_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: exynos
[New Thread 0xaf9ff050 (LWP 11610)]
[New Thread 0xaa31b050 (LWP 11611)]
[Thread 0xaa31b050 (LWP 11611) exited]
[New Thread 0xaa31b050 (LWP 11612)]
E: ../native/base/QtMain.cpp:182: E: Output audio samples: 1024 (requested: 2048)
I: ../native/gfx_es2/gl_state.cpp:136: I: GPU Vendor : ARM ; renderer: Mali-400 MP version str: OpenGL ES 2.0 ; GLSL version str: OpenGL ES GLSL ES 1.00
I: ../native/gfx_es2/gpu_features.cpp:20: I: Checking for GL driver bugs... vendor=4 model='Mali-400 MP'

Program received signal SIGSEGV, Segmentation fault.
operator==<char> (__rhs=..., __lhs=...) at /usr/include/c++/4.8/bits/basic_string.h:2497
2497							    __lhs.size())); }


(gdb) bt full
#0  operator==<char> (__rhs=..., __lhs=...) at /usr/include/c++/4.8/bits/basic_string.h:2497
No locals.
#1  SetBackgroundAudioGame (path=...) at ../UI/BackgroundAudio.cpp:185
        lock = {mtx_ = @0xef0a38}
#2  0x00092510 in MainScreen::MainScreen (this=0x19c58c0) at ../UI/MainScreen.cpp:688
No locals.
#3  0x000996a0 in Next (this=<optimized out>) at ../UI/MiscScreens.cpp:377
No locals.
#4  LogoScreen::update (this=<optimized out>, input_state=...) at ../UI/MiscScreens.cpp:386
No locals.
#5  0x000a1b28 in NativeUpdate (input=...) at ../UI/NativeApp.cpp:778
No locals.
#6  0x000ea9e0 in UpdateRunLoop () at ../Core/Core.cpp:160
No locals.
#7  0xb6dde5fa in QGLWidget::glDraw() () from /usr/lib/arm-linux-gnueabihf/libQt5OpenGL.so.5
No symbol table info available.
#8  0x01934218 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by sergiobenrocha2** [comment]
Tried with clang 3.4, and it works!

**Comment by GAMELASTER** [comment]
Build after Raspberry Pi?

**Comment by sergiobenrocha2** [comment]
Nope, Odroid U3.

**Comment by unknownbrackets** [comment]
Is this on a device that doesn't have audio working?

-[Unknown]

**Comment by sergiobenrocha2** [comment]
Nope, it's working.

**Comment by unknownbrackets** [comment]
Has this improved?

-[Unknown]

**Comment by unknownbrackets** [comment]
We've made some changes to locking in this function which might help if it hadn't improved then.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
