### ISSUE TITLE
Android install failed

### ISSUE THREAD

**Issue by miao1007** [hrydgard/ppsspp#7878]
I try to install the dev version of ppsspp on android, but failed to install.But when I install the normal version, it works fine.

Exception:[INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION]

Android Version: 4.4(daivlk)
Dev Version: ppsspp-v1.0.1-786-g0763dbc-android.apk 

Logcat：

```
D/ActivityThread(21614): handleBindApplication:com.android.defcontainer
D/ActivityThread(21614): setTargetHeapUtilization:0.75
D/ActivityThread(21614): setTargetHeapMinFree:4194304
W/ActivityManager( 1046): No content provider found for permission revoke: file:///data/local/tmp/ppsspp-v1.0.1-786-g0763dbc-android.apk
W/ActivityManager( 1046): No content provider found for permission revoke: file:///data/local/tmp/ppsspp-v1.0.1-786-g0763dbc-android.apk
I/PackageManager( 1046): Copying native libraries to /data/app-lib/vmdl658360738
W/Resources( 1046): Converting to int: TypedValue{t=0x3/d=0x5 "res/drawable-xhdpi-v4/tv_banner.png" a=3 r=0x7f020002}
W/PackageParser( 1046): /data/app/vmdl658360738.tmp
W/PackageParser( 1046): java.lang.NumberFormatException: Invalid int: "res/drawable-xhdpi-v4/tv_banner.png"
W/PackageParser( 1046): 	at java.lang.Integer.invalidInt(Integer.java:137)
W/PackageParser( 1046): 	at java.lang.Integer.parse(Integer.java:374)
W/PackageParser( 1046): 	at java.lang.Integer.parseInt(Integer.java:365)
W/PackageParser( 1046): 	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)
W/PackageParser( 1046): 	at android.content.res.TypedArray.getInt(TypedArray.java:255)
W/PackageParser( 1046): 	at android.content.pm.PackageParser$Injector.parseApplication(PackageParser.java:4190)
W/PackageParser( 1046): 	at android.content.pm.PackageParser.parseApplication(PackageParser.java:2071)
W/PackageParser( 1046): 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1049)
W/PackageParser( 1046): 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:547)
W/PackageParser( 1046): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:9205)
W/PackageParser( 1046): 	at com.android.server.pm.PackageManagerService.access$2400(PackageManagerService.java:210)
W/PackageParser( 1046): 	at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:7264)
W/PackageParser( 1046): 	at android.os.Handler.handleCallback(Handler.java:733)
W/PackageParser( 1046): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageParser( 1046): 	at android.os.Looper.loop(Looper.java:136)
W/PackageParser( 1046): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ppmeis** [comment]
@miao1007 did you try with latest build actually?

**Comment by hrydgard** [comment]
Hm, that looks a bit scary. As far as I know there's nothing different about the tv_banner.png that would cause something like this....

**Comment by unknownbrackets** [comment]
This is just the apk from the buildbot, right?

I have not actually tried recent builds of PPSSPP against pre-5.0 Android...

-[Unknown]

**Comment by hrydgard** [comment]
I have, though, and it works for me... but maybe this is some broken hacked android or something.

**Comment by unknownbrackets** [comment]
We'll reopen this is there's more feedback / detail or more reports.  Closing for now, since we don't have enough information to do anything about it.

Maybe it was just a broken download of the APK even?  Please feel free to comment with more info.

-[Unknown]
