### ISSUE TITLE
gradle build - Fails to build

### ISSUE THREAD

**Issue by Krakn** [hrydgard/ppsspp#9641]
Seems that gradle is failing to pull in a dependency:

```
 1 » gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/krakn/Git/ppsspp/android/build.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.gladed.androidgitversion', version: '0.3.4']
> Could not GET 'https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/com.gladed.androidgitversion/0.3.4'.
   > java.security.ProviderException: java.security.InvalidKeyException: EC parameters error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.445 secs
```

### Steps to reproduce:

```
git clone https://ww.github.com/hrydgard/ppsspp.git
cd ppsspp
git submodule update --init --recursive
cd android
gradle build
```

I'm aware a cmake solution is in place, but I'm unable to get it building an apk.

Am I just doing it wrong? 

### Debug log snippet:
```
20:55:56.145 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'uast.jar (com.android.tools.external.com-intellij:uast:162.2228.14)' in resolver cache: /home/krakn/.gradle/caches/modules-2/files-2.1/com.android.tools.external.com-intellij/uast/162.2228.14/3d67ea648c9594d981896c40478744fdd515e713/uast-162.2228.14.jar
20:55:56.145 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'lombok-ast.jar (com.android.tools.external.lombok:lombok-ast:0.2.3)' in resolver cache: /home/krakn/.gradle/caches/modules-2/files-2.1/com.android.tools.external.lombok/lombok-ast/0.2.3/528b6f8bde3157f17530aa366631f2aad2a6cf9/lombok-ast-0.2.3.jar
20:55:56.146 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'annotations.jar (com.android.tools:annotations:25.3.0)' in resolver cache: /home/krakn/.gradle/caches/modules-2/files-2.1/com.android.tools/annotations/25.3.0/e9ba6ed99c3ba7211201158dd9212a484a1865dc/annotations-25.3.0.jar
20:55:56.149 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.057 secs
20:55:56.150 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.help' (hidden = false)
20:55:56.150 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.projects' (hidden = false)
20:55:56.150 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.tasks' (hidden = false)
20:55:56.150 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.properties' (hidden = false)
20:55:56.150 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.dependencyInsight' (hidden = false)
20:55:56.150 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.dependencies' (hidden = false)
20:55:56.150 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.buildEnvironment' (hidden = false)
20:55:56.150 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.components' (hidden = false)
20:55:56.151 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.model' (hidden = false)
20:55:56.151 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :android - Registering model element 'tasks.dependentComponents' (hidden = false)
20:55:56.151 [INFO] [org.gradle.configuration.project.BuildScriptProcessor] Evaluating project ':android' using build file '/home/krakn/Git/ppsspp/android/build.gradle'.
20:55:56.152 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for Plugin Resolution Cache (/home/krakn/.gradle/caches/3.4.1/plugin-resolution)
20:55:56.152 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on Plugin Resolution Cache (/home/krakn/.gradle/caches/3.4.1/plugin-resolution).
20:55:56.152 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on Plugin Resolution Cache (/home/krakn/.gradle/caches/3.4.1/plugin-resolution).
20:55:56.152 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache plugin-use-metadata.bin (/home/krakn/.gradle/caches/3.4.1/plugin-resolution/plugin-use-metadata.bin)
20:55:56.152 [DEBUG] [org.gradle.internal.resource.transport.http.HttpResourceAccessor] Constructing external resource: https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/com.gladed.androidgitversion/0.3.4
20:55:56.152 [DEBUG] [org.gradle.internal.resource.transport.http.HttpClientHelper] Performing HTTP GET: https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/com.gladed.androidgitversion/0.3.4
20:55:56.153 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: default
20:55:56.153 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
20:55:56.153 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {s}->https://plugins.gradle.org:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
20:55:56.153 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 17][route: {s}->https://plugins.gradle.org:443][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
20:55:56.153 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Opening connection {s}->https://plugins.gradle.org:443
20:55:56.389 [DEBUG] [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connecting to plugins.gradle.org/104.16.175.166:443
20:55:56.389 [DEBUG] [org.apache.http.conn.ssl.SSLConnectionSocketFactory] Connecting socket to plugins.gradle.org/104.16.175.166:443 with timeout 0
20:55:56.568 [DEBUG] [org.apache.http.conn.ssl.SSLConnectionSocketFactory] Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]
20:55:56.568 [DEBUG] [org.apache.http.conn.ssl.SSLConnectionSocketFactory] Enabled cipher suites:[TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
20:55:56.568 [DEBUG] [org.apache.http.conn.ssl.SSLConnectionSocketFactory] Starting handshake
20:55:56.751 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-17: Shutdown connection
20:55:56.751 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection discarded
20:55:56.751 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-17: Close connection
20:55:56.751 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 17][route: {s}->https://plugins.gradle.org:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
20:55:56.751 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.601 secs
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Build file '/home/krakn/Git/ppsspp/android/build.gradle' line: 2
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Error resolving plugin [id: 'com.gladed.androidgitversion', version: '0.3.4']
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not GET 'https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/com.gladed.androidgitversion/0.3.4'.
20:55:56.754 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
20:55:56.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:55:56.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
20:55:56.755 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
20:55:56.755 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
20:55:56.755 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
20:55:56.755 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
20:55:56.755 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 1.362 secs
20:55:56.757 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
20:55:56.757 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
20:55:56.757 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.0 secs
20:55:56.757 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Plugin Resolution Cache (/home/krakn/.gradle/caches/3.4.1/plugin-resolution)
20:55:56.757 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache plugin-use-metadata.bin (/home/krakn/.gradle/caches/3.4.1/plugin-resolution/plugin-use-metadata.bin)
20:55:56.757 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Plugin Resolution Cache (/home/krakn/.gradle/caches/3.4.1/plugin-resolution).
20:55:56.758 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/home/krakn/.gradle/caches/3.4.1/generated-gradle-jars) was closed 0 times.
20:55:56.758 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
20:55:56.758 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
20:55:56.758 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for artifact cache (/home/krakn/.gradle/caches/modules-2)
20:55:56.758 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/home/krakn/.gradle/caches/modules-2/metadata-2.23/module-metadata.bin)
20:55:56.758 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/home/krakn/.gradle/caches/modules-2/metadata-2.23/artifact-at-repository.bin)
20:55:56.758 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/home/krakn/.gradle/caches/modules-2).
20:55:56.758 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
20:55:56.863 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@70e0623f
20:55:56.863 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 10: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
20:55:56.864 [INFO] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Build file '/home/krakn/Git/ppsspp/android/build.gradle' line: 2
Error resolving plugin [id: 'com.gladed.androidgitversion', version: '0.3.4']] from daemon DaemonInfo{pid=22615, address=[848ae9e0-5a58-4385-b818-cd477f6a811d port:39283, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1493085322402, context=DefaultDaemonContext[uid=6cfdf43d-dbec-47f6-ac6c-0f048075f0ac,javaHome=/usr/lib/jvm/java-7-openjdk,daemonRegistryDir=/home/krakn/.gradle/daemon,pid=22615,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
20:55:56.865 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
20:55:56.865 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop

```

### Full stacktrace:
```
 1 » gradle build --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file '/home/krakn/Git/ppsspp/android/build.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.gladed.androidgitversion', version: '0.3.4']
> Could not GET 'https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/com.gladed.androidgitversion/0.3.4'.
   > java.security.ProviderException: java.security.InvalidKeyException: EC parameters error

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleException: Error resolving plugin [id: 'com.gladed.androidgitversion', version: '0.3.4']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:236)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$000(DefaultPluginRequestApplicator.java:63)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:90)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:88)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:189)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:184)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:88)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:156)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:233)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:230)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:160)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/com.gladed.androidgitversion/0.3.4'.
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:82)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRawGet(HttpClientHelper.java:66)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.getRawResource(HttpResourceAccessor.java:58)
	at org.gradle.plugin.use.resolve.service.internal.HttpPluginResolutionServiceClient.request(HttpPluginResolutionServiceClient.java:86)
	at org.gradle.plugin.use.resolve.service.internal.HttpPluginResolutionServiceClient.queryPluginMetadata(HttpPluginResolutionServiceClient.java:66)
	at org.gradle.plugin.use.resolve.service.internal.PersistentCachingPluginResolutionServiceClient$1.create(PersistentCachingPluginResolutionServiceClient.java:60)
	at org.gradle.plugin.use.resolve.service.internal.PersistentCachingPluginResolutionServiceClient$1.create(PersistentCachingPluginResolutionServiceClient.java:58)
	at org.gradle.plugin.use.resolve.service.internal.PersistentCachingPluginResolutionServiceClient.fetch(PersistentCachingPluginResolutionServiceClient.java:110)
	at org.gradle.plugin.use.resolve.service.internal.PersistentCachingPluginResolutionServiceClient.maybeFetch(PersistentCachingPluginResolutionServiceClient.java:103)
	at org.gradle.plugin.use.resolve.service.internal.PersistentCachingPluginResolutionServiceClient.maybeFetch(PersistentCachingPluginResolutionServiceClient.java:91)
	at org.gradle.plugin.use.resolve.service.internal.PersistentCachingPluginResolutionServiceClient.queryPluginMetadata(PersistentCachingPluginResolutionServiceClient.java:67)
	at org.gradle.plugin.use.resolve.service.internal.InMemoryCachingPluginResolutionServiceClient$1.create(InMemoryCachingPluginResolutionServiceClient.java:47)
	at org.gradle.plugin.use.resolve.service.internal.InMemoryCachingPluginResolutionServiceClient$1.create(InMemoryCachingPluginResolutionServiceClient.java:45)
	at org.gradle.plugin.use.resolve.service.internal.InMemoryCachingPluginResolutionServiceClient.getResponse(InMemoryCachingPluginResolutionServiceClient.java:76)
	at org.gradle.plugin.use.resolve.service.internal.InMemoryCachingPluginResolutionServiceClient.queryPluginMetadata(InMemoryCachingPluginResolutionServiceClient.java:42)
	at org.gradle.plugin.use.resolve.service.internal.DeprecationListeningPluginResolutionServiceClient.queryPluginMetadata(DeprecationListeningPluginResolutionServiceClient.java:48)
	at org.gradle.plugin.use.resolve.service.internal.PluginResolutionServiceResolver.resolve(PluginResolutionServiceResolver.java:84)
	at org.gradle.plugin.use.resolve.internal.CompositePluginResolver.resolve(CompositePluginResolver.java:33)
	at org.gradle.plugin.use.resolve.internal.NotNonCorePluginOnClasspathCheckPluginResolver.resolve(NotNonCorePluginOnClasspathCheckPluginResolver.java:42)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:234)
	... 66 more
Caused by: javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:113)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:89)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:80)
	... 85 more
Caused by: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
	... 99 more
Caused by: java.security.InvalidKeyException: EC parameters error
	... 99 more
Caused by: java.security.NoSuchProviderException: no such provider: SunEC
	... 99 more


BUILD FAILED

Total time: 8.276 secs
```

**Comment by hrydgard** [comment]
That's odd, this worked fairly recently. I'll look into it.

**Comment by Krakn** [comment]
Same issue here: https://github.com/ether-camp/ethereum-harmony/issues/33

I'm wagering that this may be an issue with Arch's OpenJDK version... I am left wondering why the others pull successfully though.

```
 » java -version
java version "1.7.0_131"
OpenJDK Runtime Environment (IcedTea 2.6.9) (Arch Linux build 7.u131_2.6.9-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.131-b00, mixed mode)
```

**Comment by hrydgard** [comment]
This works consistently on both my Mac and Windows PC so it's gotta be something distro-specific like OpenJDK, yeah.

**Comment by Krakn** [comment]
I must have been doing something very wrong. Reinstalled openjdk8 and everything's working.

Woohoo!
